### ISSUE TITLE
feature: Allow to 'preload' pattern

### ISSUE THREAD

**Issue by IndianBoy42** [folke/flash.nvim#10]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

I want to be able to create a version of `*/#` but with labels. I think this could reuse most of the existing code by activating `flash.jump` with the word under the cursor (`vim.fn.expand("<cword>")`) as the pattern already. 

### Describe the solution you'd like

A config option `config.search.pattern` which if given is preloaded into the state so the labels would already appear. Perhaps another config option to control whether any further keypresses would add to the pattern or not. This config option really only makes sense in the modes table or being provided in the keymapping so maybe it should be an error to put it in the global config. 

### Describe alternatives you've considered

`search.mode = function() return vim.fn.expand("<cword>") end` is close to working, I have to type one dummy character to get the labels to show up though. Perhaps instead this should be called once with an empty string when entering flash.

**Comment by folke** [comment]
This actually already works, but I haven't documented it yet:

```lua
require("flash").jump({pattern = "foo"})
```

**Comment by IndianBoy42** [comment]
What do you think about the `search.mode = function` behavior? I think calling it at the begining with the empty pattern, and if the search string it returns is nonempty, using it to have starting labels might be useful. You could have a mode that prelabels words/the current word and then use a pattern to narrow it down from there. Something like 

```lua
search.mode = function(pat)
return (vim.fn.expand"<cword>") .. pat -- pat could even be turned into a fuzzy searching pattern
end
```

**Comment by folke** [comment]
`search.mode` as a function is to change the input pattern to a regex.

When the input pattern is an empty string, currently no matches will be searched for.

Can't you achieve what you need with the below?

```lua
require("flash").jump({
  pattern = vim.fn.expand("<cword>"),
})
```

**Comment by IndianBoy42** [comment]
Yeah `pattern` solves the `*` problem I was just thinking to some other things. You know what, I think I figured out another way to do what I want. Thanks for the plugin!
