### ISSUE TITLE
feature: char api similar to jump

### ISSUE THREAD

**Issue by milisims** [folke/flash.nvim#103]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

I use `fFtT` lables when in operator mode, and only want the backdrop to happen in operator mode, accomplished with this (trimmed for relevancy) lazy setup:
```lua
return {
  'folke/flash.nvim',
  event = 'VeryLazy',
  -- char enabled
  opts = { modes = { char = { highlight = { backdrop = false } } } },
  config = function(cfg)
    local flash = require 'flash'
    flash.setup(cfg.opts)

    -- by default, the operator maps are set, but we override them here.
    local Config = require("flash.config")
    local Char = require("flash.plugins.char")
    for _, motion in ipairs({ "f", "t", "F", "T" }) do
      vim.keymap.set('o', motion, function()
        flash.jump(Config.get({
          mode = 'char',
          search = { mode = Char.mode(motion), max_length = 1 },
          highlight = { backdrop = true },
        }, Char.motions[motion]))
      end)
    end
  end,
}
```
Writing this felt hacky because I had to read the code to get a handle on what was happening, but the examples did provide enough to make this work quickly and simply.

### Describe the solution you'd like

Extract keymaps from char plugin to an API allowing keymaps in line with `flash.jump` and `flash.treesitter` for something like:
```lua
return {
  'folke/flash.nvim',
  event = 'VeryLazy',
  -- char enabled
  opts = { modes = { char = { highlight = { backdrop = false } } } },
  config = function(cfg)
    local flash = require 'flash'
    flash.setup(cfg.opts)

    for _, motion in ipairs { 'f', 't', 'F', 'T' } do
      vim.keymap.set('o', motion, function()
        -- api could obviously be whatever, but the idea is to use the config simply in the keymap
        flash.char[motion] { highlight = { backdrop = true }, jump_labels = true }
      end)
    end
  end,
}
```

### Describe alternatives you've considered

`backdrop` could be allowed to be a function like `jump_labels`, but the above solution just enables a more user friendly customizable experience, also this feature is not adding anything functionally, so is far from required, it just is confusing to use as is, and I needed to read the plugin code to have a handle on what was happening.

**Comment by folke** [comment]
I've reworked the whole config system.

`autohide` and `jump_labels` are no longer functions (but it's backward compatible,).

Added `opts.config` to allow easy dynamic configurations of flash.

Use the config below for ftFT labels and custom backdrop:

```lua
{
      modes = {
        char = {
          jump_labels = true,
          config = function(opts)
            -- autohide flash when in operator-pending mode
            opts.autohide = vim.fn.mode(true):find("no") and vim.v.operator == "y"

            opts.highlight.backdrop = vim.fn.mode(true):find("o")

            -- disable jump labels when enabled and when using a count
            opts.jump_labels = opts.jump_labels and vim.v.count == 0

            -- Show jump labels only in operator-pending mode
            -- opts.jump_labels = vim.v.count == 0 and vim.fn.mode(true):find("o")
          end,
        },
      },
    }
```

You can of course change the logic to match what you want it to do.

**Comment by gennaro-tedesco** [comment]
After the latest commits I have noticed the following behaviour (see screenshot):

I am doing `yt=` or equivalently `dt=` and it seems that flash puts the operators in visual mode first (see visual selection) and only completes the yank or delete if I manually move the cursor left or right.

https://github.com/folke/flash.nvim/assets/15387611/719512e5-f76f-490a-9595-210e04d23763

Can you reproduce it and/or is this the default behaviour you had in mind? A couple of commits ago (say until bdfda726eb9e5e87d5860cdd2f33d678cc343cdb) with 
```lua
char = {
  autohide = function(motion)
    return vim.fn.mode(true):find("no") and vim.v.operator == "y"
  end,
```
the behaviour was similar and according to the normal vim selections with `tf` (namely immediate yank/delete).

**Comment by folke** [comment]
@gennaro-tedesco that was definitely not intentional. I had switched on jump_labels for testing and accidentally committed that. Fixed now.
