### ISSUE TITLE
NeoVim version < 0.9 errors: strcharlen not found

### ISSUE THREAD

**Issue by israrwz** [folke/flash.nvim#105]
In my NeoVim 0.8.3 I installed flash.nvim using vim-plug because I'm not using LazyVim and flash would throw an error saying that the function `strcharlen` could not be found. 

I was only able to fix it after upgrading NeoVim to 0.9.1.

So maybe the project Readme file could be updated to reflect this requirement.

**Comment by folke** [comment]
I used another function that does the same. Should work now on 0.8.2
