### ISSUE TITLE
feature: Double-character labels for features like jump to line

### ISSUE THREAD

**Issue by mystilleef** [folke/flash.nvim#106]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

`HopLine` is the last feature I need from `Hop` to completely ditch it. At the moment `Flash` does not support double-character labels, so it cannot label the beginning of all lines in a document.

### Describe the solution you'd like

Maybe provide a way to temporarily override the labels list to allow double characters for certain jumps, like `jump-to-line`. 

It doesn't even have to be supported by default. It should just exist for edge cases for users who want to do weird stuff, like implementing jump-to-line in `Flash`.

Alternatively, you could just implement `FlashLine` as an edge-case solution. That way you can restrict double-character labels to just `FlashLine` until double-characters can be available universally, if possible.

### Describe alternatives you've considered

The `jump-to-line` example works but does not label all the visible lines in documents due to the limited number of single-character labels.

The only alternative so far is to use `HopLine` from `Hop` or a similar feature from other jump plugins.

### Additional context

Screenshot of flash jump-to-line just labeling a few lines.

![flashhopbug](https://github.com/folke/flash.nvim/assets/273399/45fdcf84-0e8e-4f8f-9040-76d7e66309a0)

**Comment by folke** [comment]
You disabled lower-case labels? Something must be off with your config of flash.

You should at least get 52 labels with that code

**Comment by mystilleef** [comment]
Interesting. I had set `uppercase` to `false` because I was formatting labels with `opts.match.label:upper()` and I assumed that would conflict with `uppercase` if it were set to `true`. 

After enabling `uppercase` and disabling my custom formatting, I get more labels. Unfortunately, still not enough. Also, it looks like folds might be consuming some of the labels. I've attached my config below. 

```lua
{
    "folke/flash.nvim",
    opts = {
      label = {
        uppercase = true,
        -- format = function(opts)
        --   return { { opts.match.label:upper(), opts.hl_group } }
        -- end,
      },
      modes = { treesitter = { highlight = { backdrop = true } } },
      jump = { autojump = true, nohlsearch = true },
    },
    keys = {
      ...
      {
        "<leader>l",
        mode = { "n", "x", "o" },
        function()
          require("flash").jump({
            search = { mode = "search", max_length = 0 },
            label = { after = { 0, 0 } },
            pattern = "^",
          })
          -- vim.schedule(require("user.utils").schedule_command)
        end,
        desc = "Label beginning of line",
      },
      ...
    },
  }
```

Screenshot of labels with unfolded code

![flash_unfolded](https://github.com/folke/flash.nvim/assets/273399/87cf7e77-b71f-433b-9e1e-534ebf5d332d)

Screenshot of labels with folded code

![flash_folded](https://github.com/folke/flash.nvim/assets/273399/feeefe9a-df8c-400b-ac5f-10332e337a25)

**Comment by folke** [comment]
@mystilleef I've added better handling of folds so that labels won't be callculated for folded lines

**Comment by mystilleef** [comment]
Excellent!
