### ISSUE TITLE
bug: Operator-pending line actions

### ISSUE THREAD

**Issue by rasulomaroff** [folke/flash.nvim#110]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

MacOS 14.0

### Describe the bug

First of all, I'm not really sure whether this is a flash issue or not. Please, correct me if I'm wrong, I'll appreciate it.

I use such plugins as `Comment.nvim` and `substitute.nvim`. They both have operator-pending mappings, such as `gcc` to comment a current line in `Comment.nvim` or `ss` to substitute a current line in `substitute.nvim`.
The thing is that flash's `jump` and `remote` modes don't work correctly when I use those `line` mappings, but they do when I use regular ones.

For example:
`gc` + `r` + [jump-tags] + `c` will not result into commenting a remote line. The sames goes to the `jump` mode as well.
**But** it does work when I use built-in line actions such as `yy`, `dd` or `cc` with remote/jump modes **OR** it also works if I use another motions instead of `line`, for example: `gc` + `r` + [jump-tags] + any other motion like `iw`, `aw` `h`, `j`, `k`, `l` etc (In this case it will work).

So my main questions is - "is it a bug?". It seems like that, but then - on which side? I remember when I first started using flash, remote `dd`/`yy`/`cc` didn't work as well, so it can be a similar bug?

I hope I explained it the right way so you can understand. Additionally, if it's impossible to fix or this bug is on those plugins' side, how can this be work-arounded? Are there any ways to do that?

### Steps To Reproduce

Using `Comment.nvim` plugin:
1. type `gc` to start operator-pending mode
2. type `r` to start the flash's remote mode
3. jump to the line you wanna comment using flash's labels
4. type `c` to comment the line

### Expected Behavior

Expected: to comment that line and jump back or just to comment that line (if in usual jump mode)

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "folke/flash.nvim",
    keys = {
            {
                'r',
                mode = 'o',
                function()
                    require('flash').remote()
                end,
            },
    },
    opts = {}
  },
  {
    'numToStr/Comment.nvim',
    event = 'VeryLazy',
    config = true
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
I'm checking with @echasnovski, but it seems that `gcc` is actually a normal mode keymap.

Without flash remote, try doing `gc`, then wait and then press `c`. That also won't work.

That's effectively also what happens in a remote motion

**Comment by folke** [comment]
It's as I figured.

One way to fix this is by adding `omap c _`, but there may be unwanted side-effects

**Comment by echasnovski** [comment]
Adding to previous comment, I'd recommend using `_` as separate "line" textobject in such cases (see `:h _`) . So `` gc + r + [jump-tags] + _ ``.

**Comment by rasulomaroff** [comment]
> Without flash remote, try doing gc, then wait and then press c. That also won't work.

You're right here.

Yeah, that `_` really solves the problem and what's more important it is the same for every other mapping as well: `gc` + `_` in `Comment.nvim` and `s` + `_` in `substitute.nvim`. Never heard of it, thank you both @folke @echasnovski !
