### ISSUE TITLE
feature: Search Prompt Noice Integration

### ISSUE THREAD

**Issue by hatredholder** [folke/flash.nvim#113]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

I think the **flash.nvim** search prompt is a cool idea, and I think you can make it even better if you combine it with [Noice](https://github.com/folke/noice.nvim)

### Describe the solution you'd like

When a **Noice** setting is set to true in configuration - open a **Noice** cmdline window with the flash.nvim search prompt when using regular jumps
```
prompt = {
  enabled = true,
  noice = true,
},
```
(obviously, requires [noice.nvim](https://github.com/folke/noice.nvim) to be installed)

### Describe alternatives you've considered

*No response*

**Comment by folke** [comment]
I'm not interested in adding this
