### ISSUE TITLE
bug: The cursor position is not restored after performing a remote action in VS Code.

### ISSUE THREAD

**Issue by archilkarchava** [folke/flash.nvim#114]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

MacOS 13.4

### Describe the bug

The cursor position is not restored after performing a remote action in VS Code with vscode-neovim extension.
The issue appeared in the version 1.8.0 of the `flash.nvim` plugin and is still present in the latest 1.13.1 version.
It works as expected and the cursor position is restored in VS Code in the 1.7.0 version of the `flash.nvim` plugin.

### Steps To Reproduce

1. Add `require("flash").remote()` or `require("flash").jump({
  remote_op = {
    restore = true,
    motion = true,
  },
})`) keymap.
2. Open some non-empty file in VS Code with vscode-neovim extension installed and enabled.
3. Try performing a remote action such as `dr...`.
4. The action is successfully performed, but the cursor position is not restored.

### Expected Behavior

The cursor position should be restored.

### Repro

```Lua
-- bootstrap lazy
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "folke/flash.nvim",
    version = "1.8.0",
    opts = {},
    keys = {
      {
        "r",
        mode = "o",
        function()
          require("flash").remote()
        end,
        desc = "Remote Flash",
      },
    }
  },
  -- add any other plugins here
}
require("lazy").setup(plugins)

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
That's because of this issue:
https://github.com/vscode-neovim/vscode-neovim/issues/1241

**Comment by boehmrn** [comment]
It seem like it is still an issue, although the mentioned issue is closed. Is it just me?
