### ISSUE TITLE
bug: I swapped the colon and comma keys because it makes more sense to me, but using Flash will reset my keymaps.

### ISSUE THREAD

**Issue by huwqchn** [folke/flash.nvim#115]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.2

### Operating system/version

MacOS 13.4

### Describe the bug

I swapped : and ,  but using flash will reset my keymaps
my flash opts is here:
```lua
    opts = {
      char = {
        keys = { "f", "F", "t", "T", ";", ":" },
      },
    },

```

### Steps To Reproduce

1. using lazyvim
2. import flash
3.swap , and : in your keymaps file

### Expected Behavior

swap , and : can work when using flash

### Repro

```Lua
-- using lazyvim and import "lazyvim.extras.editor.flash" then add following config
return {
    "folke/flash.nvim",
    optional = true,
    opts = {
      char = {
        keys = { "f", "F", "t", "T", ";", ":" },
      },
    },
}
```

**Comment by folke** [comment]
Check the flash docs config section for how to remap.

you probably want:

```lua
keys = { "f", "F", "t", "T", ";", [","]:":" },
