### ISSUE TITLE
feature: 2 chars jump or multiple chars jump

### ISSUE THREAD

**Issue by KPatr1ck** [folke/flash.nvim#120]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

I use this function to jump to any word like `Hopword` in <a href="https://github.com/phaazon/hop.nvim">hop.nvim</a>.

```lua
require('flash').jump({
    pattern = '.', -- initialize pattern with any char
    search = {
        mode = function(pattern)
            -- remove leading dot
            if pattern:sub(1, 1) == '.' then
                pattern = pattern:sub(2)
            end
            -- return word pattern and proper skip pattern
            return ([[\v<%s\w*>]]):format(pattern), ([[\v<%s]]):format(pattern)
        end,
    },
    label = { after = false, before = { 0, 0 }, uppercase = false },
    action = function(match, state)
        state:hide()
        require('flash').jump({
            search = { max_length = 0 },
            -- label = { distance = false },
            label = { after = false, before = { 0, 1 }, uppercase = false },
            highlight = { matches = true },
            matcher = function(win)
                return vim.tbl_filter(function(m)
                    return m.label == match.label and m.win == win
                end, state.results)
            end,
        })
    end,
    labeler = function(matches, state)
        local labels = state:labels()
        for m, match in ipairs(matches) do
            match.label = labels[math.floor((m - 1) / #labels) + 1]
        end
    end,
})
```

But I have to jump by the first char shown and then the second char.
Is possible to use 2 chars or multiple chars like `Hopword` ? Meaning that multiple chars shown at once instead one by one.

### Describe the solution you'd like

![image](https://github.com/folke/flash.nvim/assets/22954146/16752537-d884-46ae-ac94-a326df6ead0d)

### Describe alternatives you've considered

Fucntion like `Hopword` and the max length of labels can be configured.

**Comment by folke** [comment]
Change the format function to:

```lua
local function format(opts)
  -- always show first and second label
  return {
    { opts.match.label1, "FlashMatch" },
    { opts.match.label2, "FlashLabel" },
  }
end
```

**Comment by KPatr1ck** [comment]
> Change the format function to:
> 
> ```lua
> local function format(opts)
>   -- always show first and second label
>   return {
>     { opts.match.label1, "FlashMatch" },
>     { opts.match.label2, "FlashLabel" },
>   }
> end
> ```

Thx! It works very well for me. 😆

**Comment by folke** [comment]
Great! :)

**Comment by Neur1n** [comment]
> This should achieve what you want. You can adjust the hl groups for the labels in the format function:
> 
> ```lua
> local Flash = require("flash")
> 
> ---@param opts Flash.Format
> local function format(opts)
>   -- always show first and second label
>   return {
>     { opts.match.label1, opts.hl_group },
>     { opts.match.label2, "Search" },
>   }
> end
> 
> Flash.jump({
>   search = { mode = "search" },
>   label = {
>     after = false,
>     before = { 0, 0 },
>     uppercase = false,
>     format = format,
>   },
>   pattern = [[\<]],
>   action = function(match, state)
>     state:hide()
>     Flash.jump({
>       search = { max_length = 0 },
>       highlight = { matches = false },
>       label = { format = format },
>       matcher = function(win)
>         -- limit matches to the current label
>         return vim.tbl_filter(function(m)
>           return m.label == match.label and m.win == win
>         end, state.results)
>       end,
>       labeler = function(matches)
>         for _, m in ipairs(matches) do
>           m.label = m.label2 -- use the second label
>         end
>       end,
>     })
>   end,
>   labeler = function(matches, state)
>     local labels = state:labels()
>     for m, match in ipairs(matches) do
>       match.label = labels[math.floor((m - 1) / #labels) + 1]
>       -- first and second label
>       match.label1 = match.label
>       match.label2 = labels[(m - 1) % #labels + 1]
>     end
>   end,
> })
> ```

Where should I put this snippet? Inside `require("flash").setup({...})` or outside? Thanks in advance.

**Comment by KPatr1ck** [comment]
> Where should I put this snippet? Inside `require("flash").setup({...})` or outside? Thanks in advance.

I put it to configuration and add a keymap to use.

```lua
-- HopWord
vim.keymap.set({ 'n', 'x', 'o' }, 'hw', function()
    local Flash = require('flash')

    ---@param opts Flash.Format
    local function format_first_match(opts)
        -- always show first and second label
        return {
            { opts.match.label1, opts.hl_group },
            { opts.match.label2, opts.hl_group },
        }
    end

    local function format_second_match(opts)
        return {
            { opts.match.label2, opts.hl_group },
        }
    end

    Flash.jump({
        search = { mode = 'search' },
        label = { after = false, before = { 0, 0 }, uppercase = false, format = format_first_match },
        pattern = [[\<]],
        action = function(match, state)
            state:hide()
            Flash.jump({
                search = { max_length = 0 },
                highlight = { matches = false },
                label = { after = { 0, 2 }, format = format_second_match },
                matcher = function(win)
                    -- limit matches to the current label
                    return vim.tbl_filter(function(m)
                        return m.label == match.label and m.win == win
                    end, state.results)
                end,
                labeler = function(matches)
                    for _, m in ipairs(matches) do
                        m.label = m.label2 -- use the second label
                    end
                end,
            })
        end,
        labeler = function(matches, state)
            local labels = state:labels()
            for m, match in ipairs(matches) do
                match.label1 = labels[math.floor((m - 1) / #labels) + 1]
                match.label2 = labels[(m - 1) % #labels + 1]
                match.label = match.label1
            end
        end,
    })
end)
```

**Comment by Neur1n** [comment]
I got an error:

```bash
E5108: Error executing lua ...\Local\nvim\plugged\flash.nvim/lua/flash/search/init.lua:49: attempt to get length of local 'line' (a nil value)
stack traceback:
        ...\Local\nvim\plugged\flash.nvim/lua/flash/search/init.lua:49: in function '_call'
        ...\Local\nvim\plugged\flash.nvim/lua/flash/search/init.lua:74: in function 'get'
        ...ppData\Local\nvim\plugged\flash.nvim/lua/flash/cache.lua:87: in function 'get_state'
        ...ppData\Local\nvim\plugged\flash.nvim/lua/flash/state.lua:283: in function '_update'
        ...ppData\Local\nvim\plugged\flash.nvim/lua/flash/state.lua:248: in function 'update'
        ...ppData\Local\nvim\plugged\flash.nvim/lua/flash/state.lua:140: in function 'new'
        ...pData\Local\nvim\plugged\flash.nvim/lua/flash/repeat.lua:51: in function 'get_state'
        ...ata\Local\nvim\plugged\flash.nvim/lua/flash/commands.lua:8: in function 'jump'
        C:\Users\myid\AppData\Local\nvim/lua/plugconf/flash.lua:13: in function 'hopword'
        C:\Users\myid\AppData\Local\nvim/lua/plugconf/flash.lua:55: in function 'setup'
        [string ":lua"]:1: in main chunk
```

**Comment by Neur1n** [comment]
Related code: https://github.com/folke/flash.nvim/blob/967117690bd677cb7b6a87f0bc0077d2c0be3a27/lua/flash/search/init.lua#L48

I got a `local line` of `nil` value, while launching neovim with or without opening a file.

**Comment by vinoff** [comment]
Any idea on how to have rainbow colors on this hop-like behaviour?
