### ISSUE TITLE
feature: make `f` (resp. `F`) always go forward (resp. backward)

### ISSUE THREAD

**Issue by tizot** [folke/flash.nvim#124]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

First, thanks for this great plugin! 👏 

Small frustration on my end, since I am switching from `mini.jump`: when I use `f` or `F`, the repeat behaviour of `f` and `F` depends on the initial movement. It adds some cognitive load, and is not always intuitive (imho).

### Describe the solution you'd like

I think it would be nice to have a behaviour similar to `mini.jump` where the `fFtT` motions always go in the same direction, whatever the initial motion.
For example:
- `fa` jumps to the next `a`, and subsequent `f` continues forward but subsequent `F` jump backward
- `Fa` jumps to the previous `a`, and subsequent `F` continues backward but subsequent `f` jump forward
(of course, similar behaviour for `t`/`T`).

### Describe alternatives you've considered

Maybe it is possible to override the default `f` and `F` mappings, but I could not find a way (I am not fluent in Lua unfortunately ^^)

**Comment by folke** [comment]
Check the docs for `char_actions` to achieve what you want

**Comment by Camille-Upway** [comment]
Works like a charm. Thanks! 🙏

**Comment by tizot** [comment]
Works like a charm. Thanks! 🙏
