### ISSUE TITLE
bug: Disabling multi-line search doesn't work when search wrapping is enabled

### ISSUE THREAD

**Issue by mystilleef** [folke/flash.nvim#126]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

master

### Operating system/version

Fedora Linux

### Describe the bug

`multi_lines = false` is ignored when `search = { wrap = true}`.

### Steps To Reproduce

1. Disable multi-line search in `modes -> char`
2. Enable search wrapping in `modes -> char`
3. Use `f` to search for a character
4. It'll search for the character in multiple lines

### Expected Behavior

Disabling multi-line search should be respected when search wrapping is enabled.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "folke/flash.nvim", opts = {modes = {char = {multi_lines = false, search = {wrap = true}}}}},
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Can't reproduce this.
The config below will still only show matches on the current line.

```{
  modes = {
    char = {
       search = {wrap = true},
       multi_line = false
    }
  }
}
