### ISSUE TITLE
bug: The current match highlight alternating when jump_lables is true

### ISSUE THREAD

**Issue by KPatr1ck** [folke/flash.nvim#127]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-578+g91aeaeef6

### Operating system/version

Ubuntu 18.04

### Describe the bug

1. Type `fs` to search char "s" ![image](https://github.com/folke/flash.nvim/assets/22954146/1e6bef14-1ce5-454e-bb3c-ca1d6231731b)
2. Type `f` again to jump to next match, and the background current match is dark grey ![image](https://github.com/folke/flash.nvim/assets/22954146/df633e3d-e174-493c-8278-a79e5c49336f)
3. Type `f` again, the background color get back to the lighter ![image](https://github.com/folke/flash.nvim/assets/22954146/ce3fc209-ce60-4bb7-ab5c-c037cee563cf)

### Steps To Reproduce

as described above 

### Expected Behavior

The hl of current match should be consistent when jump_lables is true.

**Comment by folke** [comment]
That's a Neovim issue. The native cursor only sometimes seems to get properly updated.

**Comment by KPatr1ck** [comment]
> That's a Neovim issue. The native cursor only sometimes seems to get properly updated.

But I found everything all right when jump_lables is set to false. So wired...

**Comment by folke** [comment]
without jump labels, flash is not waiting for input. It's the blocking input that causes the cursor weirdness
