### ISSUE TITLE
feature: Highlight group for "char" current selection

### ISSUE THREAD

**Issue by brianfabre** [folke/flash.nvim#131]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

When searching with "f" in char mode, the current selection is hard to see with my colorscheme. For example, if I press "f" to search for "t", all the "t"s are easy to see except the first "t" . I didn't see an option to change the highlight group for that specific instance. Is there any way to add another highlight group for this?

### Describe the solution you'd like

I would like another highlight group to change the highlights for the first instance of a "char" search.

### Describe alternatives you've considered

n/a

**Comment by towry** [comment]
https://github.com/folke/flash.nvim#-highlights

![截屏2023-07-06 12 27 19](https://github.com/folke/flash.nvim/assets/8279858/f873760e-eb4f-405d-af0a-c3fb1a54be7b)

pretty clear to me.

**Comment by brianfabre** [comment]
> https://github.com/folke/flash.nvim#-highlights
> 
> ![截屏2023-07-06 12 27 19](https://user-images.githubusercontent.com/8279858/251342030-f873760e-eb4f-405d-af0a-c3fb1a54be7b.png)
> 
> pretty clear to me.

That is because you have a different colorscheme. It would be useful if you could change the highlight group of, in your picture, the "e" that is white.
