### ISSUE TITLE
feature: Better warnings (or support?) for files containing binary data

### ISSUE THREAD

**Issue by TinusgragLin** [folke/flash.nvim#133]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

I was working on a custom half-binary half text file format just for my personal interest, and found that `flash.nvim` (and `hop`, but surprisingly not `leap`) does not support files containing binary data or kindly warn about this (it just crashes). After some digging I found that calls to certain functions (e.g. `vim.fn.charidx`, `vim.fn.byteidx`) assuming input being text string are not protected (using e.g. `pcall`),  so their errors just crashes `flash.nvim`.

### Describe the solution you'd like

Simply protecting calls to functions requiring its input being text string, capturing related errors and warning the user is good enough to me. Though if anyone is interested in working to support searching text parts of a binary file, I will be very grateful to such effort!

### Describe alternatives you've considered

However, I understand this is quite a niche need and currently I am about to finish the whole custom half-text half-binary file format business anyway, so feel free to skip this issue if this just isn't that necessary!

**Comment by folke** [comment]
yeah, this does seem not really a typical use-case
