### ISSUE TITLE
feature: clear lsp extmarks when when using flash

### ISSUE THREAD

**Issue by A-Lamia** [folke/flash.nvim#135]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

when using flash, (search) the highlights from `LspReferenceRead`, `LspReferenceText`, `LspReferenceWrite` are left on the screen.

### Describe the solution you'd like

Clear `LspReferenceRead`, `LspReferenceText`, `LspReferenceWrite` when flash command is first run.

### Describe alternatives you've considered

in flashes plugin deceleration where the functions are bound to the key, clearing the extmarks before the command is run.

**Comment by folke** [comment]
that's out of scope for flash

**Comment by A-Lamia** [comment]
all good, I have this issue solved on my end.
