### ISSUE TITLE
feature: clear highlight after jumping to first match with `<CR>`

### ISSUE THREAD

**Issue by gennaro-tedesco** [folke/flash.nvim#139]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

Not a problem, and likely I have misunderstood some configuration options. When in search mode, say with `/`, flash clears the search highlight when selecting a match via a certain label; however, such isn't the case when jumping to the first match via `<CR>`. I tried setting `jump = {nohlsearch = true}` to no avail (both in the general `jump` configuration and in `modes.search.jump`)

### Describe the solution you'd like

Clear search highlight after jumping to first match via `<CR>`.

### Describe alternatives you've considered

Re-mapping `<CR>` to explicitly clear the search highlights too.

### Additional context

I remember seeing a related discussion either as issue or in the "Discussions" section (??), but I couldn't find it (hence sorry if this has been discussed already).

**Comment by folke** [comment]
That's to be expected. When hitting `<CR>` during a regular search, flash is not involved. That's just doing a regular search.

To achieve what you want you could just
