### ISSUE TITLE
bug: repeat detection code doesn't work well when using a `:lua` keymap rhs

### ISSUE THREAD

**Issue by folke** [folke/flash.nvim#140]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

all

### Operating system/version

linux (arch btw)

### Describe the bug

an rhs of `:lua require("flash").jump()<CR>` will trigger the repeat code because of the dot.

### Steps To Reproduce

Create an rhs with `:lua`

### Expected Behavior

Should not trigger repeat

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "folke/flash.nvim", opts = {} },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
test

**Comment by schoblaska** [comment]
As a workaround, you can use bracket notation: `[[:lua require("flash")["jump"]()<CR>]]`

**Comment by folke** [comment]
You can also just use a function or a `<cmd>` string instead

**Comment by folke** [comment]
Fixed by documenting this.
