### ISSUE TITLE
bug: `nohlsearch = false` still clear the search highlights

### ISSUE THREAD

**Issue by woosaaahh** [folke/flash.nvim#142]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-657+g19fb573ad

### Operating system/version

Linux/Arch

### Describe the bug

Hi !

First of all, thanks a lot folke and all the contributors for this amazing plugin !!!

I understand the `<CR>`/"regular search" part from this issue #139.
But is this normal/expected that setting `nohlsearch = false` everywhere still clear the search highlights ?

### Steps To Reproduce

1. I run `nvim -u minimal_code.lua`
1. I edit the file `:e minimal_code.lua`
1. I search for 'hlsearch' `/hlsearch`
1. I type a label

Then the cursor jump at the right location but the highlights are cleared, even with `nohlsearch = false`.
If I use the keymap (`s`) defined at the end of the file, the highlights are still cleared.

Sorry but I don't use any plugins managers. If the minimal code must use 'lazy', then I'll try with it.

### Expected Behavior

Search highlights are still displayed after a jump when using `nohlsearch = false`.

### Repro

```Lua
local flash = require("flash")

flash.setup({
	jump = {
		nohlsearch = false,
	},
	modes = {
		search = {
			enabled = true,
			jump = { nohlsearch = false },
		},
	},
})

vim.keymap.set({ "n", "o", "x" }, "s", function()
	flash.jump({
		jump = {
			nohlsearch = false,
		},
	})
end, { desc = "Flash" })
```

**Comment by folke** [comment]
If you jump, the search is cancelled, so there was nothing to clear.

However, I just added support for showing search highlights when `nohlsearch=false` and `jump.register = true`

**Comment by woosaaahh** [comment]
Oh... then I'm really sorry for not understanding the use case for this option !

Thanks a lot for your work and this plugin ! 

I'm trying `flash` until the end of the week and it's pretty cool so far ! 
Who know, maybe I'll ditch `sj` !
