### ISSUE TITLE
feature: Disable char motions (fFtT) just for a certain mode, e.g., visual/operator-pending mode.

### ISSUE THREAD

**Issue by haoming-li-ling** [folke/flash.nvim#145]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

When executing things like `dt<char>`, the enhanced motions don't make much sense; pressing `t` makes jumps to further `<char>`'s, but deletion is not extended to those targets. I would rather that I can disable enhanced `fFtT` in operator-pending mode altogether.

### Describe the solution you'd like

A config option for `char` as a list of modes in which it is enabled.

### Describe alternatives you've considered

Perhaps pressing `t` again should extend the deletion to further targets? But I guess this improvement and the solution suggested above should both be implemented.

**Comment by folke** [comment]
That already exists. It's even mentioned as an example. Check the config section of the docs

**Comment by haoming-li-ling** [comment]
I am not sure that example is the one I need, if you are talking about the example where you set `fFtT` to use labels.

**Comment by folke** [comment]
Go to the config section and expand default settings
![image](https://github.com/folke/flash.nvim/assets/292349/9e7d3639-6084-4a7d-a704-7d645d54bc86)
