### ISSUE TITLE
feature: recalculate labels

### ISSUE THREAD

**Issue by kaiphat** [folke/flash.nvim#147]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

My setup:
```lua
flash.setup {
  labels = 'fdkjaslhpioqwertyuzxcvbnm'
}
```
This labels was sorted by convenience for  me.
Example:
![image](https://github.com/folke/flash.nvim/assets/53742299/3fe75f4a-6ab0-4d26-881c-a4c4e28b3f9c)
I run `flash.jump()` and type `c`
![image](https://github.com/folke/flash.nvim/assets/53742299/c6f7addc-fee6-4e1c-95d7-8037c613d5c5)
Then i type `o`
![image](https://github.com/folke/flash.nvim/assets/53742299/101715d1-4456-4681-970f-f6f9491d57d0)
And got not very comfortable labels. I expect `fdkj` in this case.
Can you add flag to config `label = { is_recalculated = true }` 

### Describe the solution you'd like

-

### Describe alternatives you've considered

-

**Comment by folke** [comment]
You can now set `opts.label.reuse = "none"`. 

Be aware that labels will now possibly change whenever you type extra characters for the search pattern, which is not great.

**Comment by kaiphat** [comment]
I thought it was implemented yet. Thank you!
