### ISSUE TITLE
bug: T/F operator movement includes current character

### ISSUE THREAD

**Issue by andrevmatos** [folke/flash.nvim#149]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0-dev-c379d72

### Operating system/version

NixOS unstable (current)

### Describe the bug

Doing some backwards char operator movement with T/F includes the current character, which deviates from the native neovim T/F behavior, and can be unexpected for anyone used to how vim char operators behave.

### Steps To Reproduce

1. Imagine the following line and cursor position:
```
abcdefg
     ^
```
2. Command: `dTb`
3. Result:
```
abg
  ^
```
4. The above (`f` being deleted as well) also happens with `dF` command, although that includes the target `b`, as expected. This affects other commands as well, like yank.

### Expected Behavior

Same as vim's, current character is kept:
```
abfg
  ^
```

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "folke/flash.nvim", opts = {} },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by emxxjnm** [comment]
seems to be a similar issue :)

flash.nvim opts
```
opts = {
  jump = {
  	pos = "end",
  },
  modes = {
    char = {
      jump_labels = function(motion)
        return vim.v.count == 0 and motion:find("[ftFT]")
      end,
    },
  },
}
```

steps to reproduce

```
abcd
^
```
press `dtd<ESC>`  and  I got this

```
bcd
^
```
expect
```
abcd
^
```

**Comment by folke** [comment]
@emxxjnm your problem is also fixed. `esc` now properly cancels operator pending mode

**Comment by andrevmatos** [comment]
Thank you for your prompt support and great plugin!
