### ISSUE TITLE
bug: t motion with custom char_actions

### ISSUE THREAD

**Issue by sudo-tee** [folke/flash.nvim#152]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

neovim-0.10.0~ubuntu1+git202307111704-06694203e-9b397864c

### Operating system/version

WSL Windows 10

### Describe the bug

When using jump labels with `t-T` motion custon `char_actions` don't work. It does not happen with and `f-F` motions where custom `char_actions` works

here is my config example 

```
{
  modes = {
    char = {
      label = { exclude = "hjkliardcn[]" },
      jump_labels = true,
      char_actions = function(motion)
        return {
          ["n"] = "next",
          ["N"] = "prev",
          ["]"] = "next",
          ["["] = "prev",
        }
      end,
    },
  },
  }
  ```

If I copy the full char_actions from the default config even the `;` `,` actions don't work anymore in the `t-T` motion

### Steps To Reproduce

1. start a `t` motion or a `vt` 
2. enter the character to find
3. hit custom keys in the char_actions ex `n`  (I like to have it consistent with nvim `/` search)
4. Observe the jump to next or previous not working

If I do the same with a `f-F` motion it works properly.

### Expected Behavior

Hitting the char in the char_actions should behave the same as the `f-F` motion

### Repro

```Lua
-- My `init.lua` is the one from LazyVim
```

**Comment by sudo-tee** [comment]
After more testing,  If after the motion `t-T`  I hit the `;` or the `,`  then now the registered custom `char_actions` will start to work.

**Comment by folke** [comment]
Should be fixed now! Thank you for reporting this.
