### ISSUE TITLE
feature: extends char motion (f,t,F,T) for far character

### ISSUE THREAD

**Issue by tuanbass** [folke/flash.nvim#155]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

When using char motion, it's ok if I want to move to "near" char, if it can fit in 1 char label. 
But I have no way to move to a character that is "far" from current location, as no label attached for it. 
is anyway to assign 2 chars - labels for these chars? 

![image](https://github.com/folke/flash.nvim/assets/9334023/b26ca9dd-bee2-4a7a-932d-d1c1cd93caf8)

Last but not least, thanks for the excellent plugin.

### Describe the solution you'd like

Assign 1-char label to "near" , and 2-chars labels to "far" characters. 

### Describe alternatives you've considered

It's just like how the Hop plugin did.

**Comment by folke** [comment]
For far jumps you should use regular jump for that where you can narrow down the target
