### ISSUE TITLE
bug：failed to enter a colon (use LazyVim)

### ISSUE THREAD

**Issue by lingllqs** [folke/flash.nvim#157]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0-dev

### Operating system/version

archlinux kernel 6.4.3

### Describe the bug

vim.api.nvim_set_keymap("n", ";", ":", { noremap = true, silent = true })

This line is invalid in my configuration file (~/.config/lua/config/keymaps.lua)
when I press semicolon (;) in normal mode, this key mapping results seem to repeat  the previous search (t, T, f, F) instead of typing a colon (:)

### Steps To Reproduce

1. in normal mode
2. press semicolon

### Expected Behavior

typing a colon

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "folke/flash.nvim", opts = {} },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Check the flash.nvim docs to change or delete the mapping for `;`

`;` is the default Neovim mapping for next ftFT

**Comment by folke** [comment]
config section and docs for `opts.modes.char.keys`

**Comment by lingllqs** [comment]
thanks a lot, but a new problem arises, When I delete or modify the semicolon in the keys list, I need to press the semicolon twice to enter command mode, and a semicolon has already been entered in the prompt box

**Comment by lingllqs** [comment]
I think accommodating LazyVim is the right thing to do
