### ISSUE TITLE
feature: char operator pending mode to accept count

### ISSUE THREAD

**Issue by andrevmatos** [folke/flash.nvim#159]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

When trying to use operator pending mode with char jump (e.g. `y2t)`), I can't select the 2nd or 3rd `)`, it always select the next/prev one.

### Describe the solution you'd like

char operator pending mode should accept a count (as native tT/fF jumps), and perform the operation up to the respective position.

### Describe alternatives you've considered

I could enable the labels for fF/tT if willing to reach the other characters, or use the normal jump; but it'd be cool for this feature to accept count, to stay as close as possible/have feature parity to the native command.

**Comment by folke** [comment]
Should be fixed now. Thank you for reporting!

**Comment by andrevmatos** [comment]
Working perfectly with any count now; thanks!
