### ISSUE TITLE
feature: Multiple patterns

### ISSUE THREAD

**Issue by ribelo** [folke/flash.nvim#16]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

Flash may allow for a more structured navigation through the code, which will be easier to define and more enjoyable to write than treesitter queries.

Defining multiple patterns such as `{"local", "function", "for", ...}` can facilitate faster movement through the code. In my opinion, it is generally much easier to choose a letter on the screen than to learn thousands of shortcuts for every occasion, like `go to next class`, and every other `[...` etc.

### Describe the solution you'd like

I would like `pattern` accept a `string[]` so that we can define the most important patterns to jump to for language using a keyboard shortcut. An even better option would be to have the ability to configure by language or filetype, but this can be worked around with autocmd.

### Describe alternatives you've considered

An alternative is to write it every time by hand like now. Another option may be to finally learn treesitter queries :)

**Comment by folke** [comment]
You can already do this:

```lua
require("flash").jump({
  search = { mode = "search" },
  pattern = "local\\|function\\|for"
})
