### ISSUE TITLE
bug: attempt to index up value 'options' (a nil value)

### ISSUE THREAD

**Issue by ShIRannx** [folke/flash.nvim#162]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

MacOs 12.5.1

### Describe the bug

Flash treesitter do not work. The package manager I used is packer.
<img width="1512" alt="image" src="https://github.com/folke/flash.nvim/assets/72802064/16dd04c0-09e9-48b0-8edc-322aa70a6358">

### Steps To Reproduce

1. append flash to packer install list.
<img width="414" alt="image" src="https://github.com/folke/flash.nvim/assets/72802064/4a446b24-cdf6-4783-af5f-a322ad7917fd">
2. bind the key. 
<img width="1152" alt="image" src="https://github.com/folke/flash.nvim/assets/72802064/92c8daab-3e42-498b-9b28-5f43e281bb9b">
3. use the '<leader><leader>s'.

### Expected Behavior

as README-like 

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "folke/flash.nvim", opts = {} },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by max397574** [comment]
what you're showing in the screenshot is obviously from a plugin installed with packer.nvim
you should clean up that folder

**Comment by folke** [comment]
So, since this is packer, you'll have to use a proper closure to call flash. The readme also shows a closure instead of how you did it

**Comment by techcaotri** [comment]
I

> ### Did you check docs and existing issues?
> * [x]  I have read all the flash.nvim docs
> * [x]  I have searched the existing issues of flash.nvim
> * [x]  I have searched the existing issues of plugins related to this issue
> 
> ### Neovim version (nvim -v)
> 0.9.1
> 
> ### Operating system/version
> MacOs 12.5.1
> 
> ### Describe the bug
> Flash treesitter do not work. The package manager I used is packer. <img alt="image" width="1512" src="https://user-images.githubusercontent.com/72802064/253809960-16dd04c0-09e9-48b0-8edc-322aa70a6358.png">

I faced the exact same issue and then realized I missed the `opts = {}` part in the plugin's declaration. Adding it fixed the issue for me:
```
{
    'folke/flash.nvim',
    opts = {},
   ...
```
Sometimes we have to do "exactly" as the README says.

**Comment by folke** [comment]
Right! I just updated flash so that in that case I run setup automatically
