### ISSUE TITLE
bug: not work when searching

### ISSUE THREAD

**Issue by Asthestarsfalll** [folke/flash.nvim#164]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.0

### Operating system/version

manjaro

### Describe the bug

I use `AstroNvim` to configure my neovim, it does't work when searching:
![2023-07-17_17-20](https://github.com/folke/flash.nvim/assets/72954905/d30b1e9e-5df2-4784-b845-a23d8f7f06db)

### Steps To Reproduce

Not sure how to reproduce it.

### Expected Behavior

It should behave like what README says.

### Repro

```Lua
I can't offer the minimal init.lua, bucause it works well when I follow the example init.lua
```

**Comment by folke** [comment]
Pretty sure the flash plugin is simply not loaded.

**Comment by Asthestarsfalll** [comment]
> Pretty sure the flash plugin is simply not loaded.

but it works well in "s" and "tTfF" mode

**Comment by folke** [comment]
Did you meanually add flash?
If not, maybe search is disabled?
Best to check in the Astronvim repo

**Comment by Asthestarsfalll** [comment]
> Did you meanually add flash? If not, maybe search is disabled? Best to check in the Astronvim repo

I solved this, because I missing the `opts` option in configuration....
