### ISSUE TITLE
bug: label is displayed in wrong position for tab

### ISSUE THREAD

**Issue by ycycyyc** [folke/flash.nvim#167]
### Did you check docs and existing issues?

- [x] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.2-dev-112+g65fc17b34

### Operating system/version

macos 13.04

### Describe the bug

label is displayed in wrong position for tab.

### Steps To Reproduce

0. I want to show the label before the match. 
1. text:
```
package main

func main() {
        return
}
```
There is a tab before the string "return".
```
package main

func main() {
/*it's  a tab*/return
}
```
2. press ‘/’ to search “return”
3.  
![image](https://github.com/folke/flash.nvim/assets/30541266/d377b0d3-c6d5-4a6d-b0ec-d923a8fab060)
the label "a" is not close to "return"
4. If it is four spaces, it works correctly.
![image](https://github.com/folke/flash.nvim/assets/30541266/ebd17782-fe03-4198-ae3c-fdd5d75c320b)

### Expected Behavior

label is close to the matching string

### Repro

```Lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
        vim.fn.system({
                "git",
                "clone",
                "--filter=blob:none",
                "https://github.com/folke/lazy.nvim.git",
                "--branch=stable", -- latest stable release
                lazypath,
        })
end

vim.opt.rtp:prepend(lazypath)

require("lazy").setup({

        {
                "folke/flash.nvim",
                event = "VeryLazy",
                opts = {
                        label = {
                                current = true,
                                after = false, ---@type boolean|number[]
                                before = true,
                        },
                },
        },
})
```

**Comment by folke** [comment]
That's actually correct behavior. The label is shown on the byte position of the previous character, which is a tab character in this case
