### ISSUE TITLE
What am I missing?

### ISSUE THREAD

**Issue by archite** [folke/flash.nvim#169]
So, LazyVim recently forced this on me and I was looking locally through its source and noticed that with flash.nvim on, One cannot run `/flash` to search for occurrences of flash. Or anything beginning with `f` unless toggling flash. Doing that every time would be tedious and at that point, disabling it would make the most sense but I think it has promise to help my work flow.

So, what am I missing. The docs appear to be geared towards someone who used one of the tools you replicated so what sets this apart and, for me at least, how can I search for things that start with `[fFtT]` since that's broken without toggling every time.

**Comment by folke** [comment]
What do you mean? Searching for anything including ftFT works just fine.
Can you give me an example buffer text and a search that doesn't work?

**Comment by archite** [comment]
Searching for flash for example is not possible without disabling flash.

**Comment by folke** [comment]
Yes, you already mentioned that however searching works fine for me and the thousands of flash.nvim users.

So please provide a proper repro as instructed in the issue template with the exact steps.

**Comment by archite** [comment]
I see. Maybe it’s a conflict with other plugins. I’ll try and reproduce with a standard LazyVim setup and if that works, I’ll track down the conflicting config.

Not sure off hand what else is watching my keystrokes on standard vim search.

Regardless, I enjoy all your work so I don’t mind researching the root cause. Only asked to see if I was missing something.

Keep up the great work and know that your are appreciated!

**Comment by archite** [comment]
Here is what it's like trying to search for `flash` in this doc (ignore the missing fonts please):

[![asciicast](https://asciinema.org/a/VWA5dzWNN6LSI575FAjStVhAD.svg)](https://asciinema.org/a/VWA5dzWNN6LSI575FAjStVhAD)

I've tested this in the docker image using stock LazyVim config and same issue.

So, it appears that what I was seeing happens when a match is not found. That is what I was missing. I think I'll try using the trigger option to ensure it doesn't jump if the search item doesn't exist.

**Comment by thenbe** [comment]
One way around this is the following:

```lua
opts = {
	modes = {
		search = {
			enabled = false, -- automatically exits out of search mode when no match (because we pressed a label)
		},
	},
}
```
