### ISSUE TITLE
bug: Is f/F designed to work like this?

### ISSUE THREAD

**Issue by karambaq** [folke/flash.nvim#173]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-601+gd55d7646c

### Operating system/version

macOS 13.2.1

### Describe the bug

When I'm hitting `f` I don't have shortcuts to different symbols, they all just highlighted.

<img width="610" alt="image" src="https://github.com/folke/flash.nvim/assets/14233969/08eabe35-84c6-4b02-8de1-c57e6f244a46">

### Steps To Reproduce

Hit `f` and any symbol

### Expected Behavior

With flit after hitting `f` I can see symbols to jump to specific symbol

<img width="552" alt="image" src="https://github.com/folke/flash.nvim/assets/14233969/f739f750-e30c-4ba8-8b6c-ab43d2d4eeff">

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	"folke/tokyonight.nvim",
	{ "folke/flash.nvim", opts = {} },
	-- add any other plugins here
	-- return {
	"folke/flash.nvim",
	event = "VeryLazy",
	vscode = true,
	opts = {},
	keys = {
		{
			"s",
			mode = { "n", "x", "o" },
			function()
				require("flash").jump()
			end,
			desc = "Flash",
		},
		{
			"S",
			mode = { "n", "o", "x" },
			function()
				require("flash").treesitter()
			end,
			desc = "Flash Treesitter",
		},
		{
			"r",
			mode = "o",
			function()
				require("flash").remote()
			end,
			desc = "Remote Flash",
		},
		{
			"R",
			mode = { "o", "x" },
			function()
				require("flash").treesitter_search()
			end,
			desc = "Treesitter Search",
		},
	},
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
flash implements `ftFT` like the regular Neovim motions.
If you rather have the jump labels, then set `opts.modes.char.jump_labels = true`

This is mentioned in the docs and also in an example in the docs

**Comment by karambaq** [comment]
Sorry, thanks!
