### ISSUE TITLE
bug: Flash breaks repeat with `.` for deletions like `df,` and `dt,`

### ISSUE THREAD

**Issue by vogler** [folke/flash.nvim#174]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.0

### Operating system/version

macOS 13.4 (22F66)

### Describe the bug

Flash breaks repeat with `.` for deletions like `df,` and `dt,`.

From https://github.com/folke/flash.nvim/issues/40#issuecomment-1644064109

### Steps To Reproduce

```console
$ cat flash.test
foo, bar, baz // df,
foo, bar, baz // dt,
```
The first `df,` deletes up to including the `,` but when repeating it with `.` it does not:
![Recording 2023-07-21 at 11 40 12](https://github.com/folke/flash.nvim/assets/493741/616f3a78-8fbb-46e4-93de-e7139886df10)

It's not specific to the character `,`. Same problem with e.g. ` `.

### Expected Behavior

`.` for `df,` should always delete up to including the next `,` and `dt,` up to before the next `,`.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "folke/flash.nvim", opts = {} },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by max397574** [comment]
to me this look like it just deletes the same amount of characters again

**Comment by folke** [comment]
Sorry, but the repro does not reproduce this. For me it still all works as it should.

Save the below to a file `repro.lua` and run it with `nvim -u repro.lua repro.lua`
Your test text is as the bottom.

```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "folke/flash.nvim", opts = {} },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
-- foo, bar, baz // df,
-- foo, bar, baz // dt,

**Comment by folke** [comment]
@max397574 were you able to reproduce this issue as well?

**Comment by max397574** [comment]
for me everything works perfectly with the repro

**Comment by folke** [comment]
@vogler can you please list the exact keys you type?
The fact that the highlights clear in your video is not normal. Highlights should stay on.

Keys I type for the `df` example: `df,..`
And same for dt `dt,..`

**Comment by vogler** [comment]
Same keys, here you go:

https://github.com/folke/flash.nvim/assets/493741/1ebdc504-ad0f-474e-b554-c90dfe1edf42

**Comment by max397574** [comment]
are you on the latest stable release?

**Comment by vogler** [comment]
Yes
![image](https://github.com/folke/flash.nvim/assets/493741/b3b46cb4-74a3-47ab-98c6-b0422dbcea77)

**Comment by max397574** [comment]
I meant the neovim version

**Comment by folke** [comment]
I tested on the latest nightly and on stable.

**Comment by max397574** [comment]
also tested on both of this now and it works
but notice that @vogler uses 0.9.0 and latest stable is 0.9.1
perhaps that could be an issue

**Comment by folke** [comment]
@vogler does your build include LuaJit? That's a requirement for flash.nvim. puc.lua is not supported

**Comment by vogler** [comment]
Upgraded nvim 0.9.0 -> 0.9.1 and now it works.

**Comment by vogler** [comment]
Just checked the [release notes of 0.9.1](https://github.com/neovim/neovim/releases/tag/v0.9.1), but didn't see anything suspicious.
@max397574 Weird that you didn't have the issue on 0.9.0. I was using the default version from `brew install neovim`.

**Comment by max397574** [comment]
I was using the release version, installed with bob
