### ISSUE TITLE
bug: E5108: Error executing lua ...e\pack\packer\start\flash.nvim/lua/flash/search/init.lua:58: ...ta\site\pack\packer\start\flash.nvim/lua/flash/ acks.lua:28: cannot resolve symbol 'search_match_lines': <d5>Ҳ<bb><b5><bd><b6><a8><b5>ĳ<cc><d0><f2><a1><a3> 

### ISSUE THREAD

**Issue by mrthere3** [folke/flash.nvim#175]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.3

### Operating system/version

windows

### Describe the bug

E5108: Error executing lua ...e\pack\packer\start\flash.nvim/lua/flash/search/init.lua:58: ...ta\ ite\pack\packer\start\flash.nvim/lua/flash/hacks.lua:28: cannot resolve symbol 'search_match_lines': <d5>Ҳ<bb><b5><bd><b6><a8><b5>ĳ<cc><d0><f2><a1><a3>                                                                                                                                               stack traceback:                                                                                          [C]: in function 'error'                                                                          ...e\pack\packer\start\flash.nvim/lua/flash/search/init.lua:58: in function '_call'               ...e\pack\packer\start\flash.nvim/lua/flash/search/init.lua:74: in function 'get'                 ...ta\site\pack\packer\start\flash.nvim/lua/flash/cache.lua:87: in function 'get_state'           ...ta\site\pack\packer\start\flash.nvim/lua/flash/state.lua:283: in function '_update'            ...ta\site\pack\packer\start\flash.nvim/lua/flash/state.lua:248: in function 'update'             ...ta\site\pack\packer\start\flash.nvim/lua/flash/state.lua:380: in function 'step'               ...ta\site\pack\packer\start\flash.nvim/lua/flash/state.lua:413: in function 'loop'               ...site\pack\packer\start\flash.nvim/lua/flash/commands.lua:9: in function 'jump'

### Steps To Reproduce

just use keymap with flash

### Expected Behavior

If you are experiencing this issue when running the <cmd>lua require("flash").jump()<cr> command in Neovim and it turns the whole buffer into an empty color, and then attempting to jump results in the error message.it seems like there is a problem with the Flash.nvim plugin. but the command <cmd>lua require("flash").treesitter()<cr> is working fine  and

**Comment by folke** [comment]
Works fine for me. Make sure you have a proper Neovim version installed with LuaJit

**Comment by mrthere3** [comment]
I updated to nvim 0.9 and it's resolved ,thanks!!!
