### ISSUE TITLE
feature: Jump to search pattern outside of view

### ISSUE THREAD

**Issue by TxHawks** [folke/flash.nvim#177]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

Thanks for a great plugin!

When searching, I often search for an instance of a keyword that isn't currently on the screen, and it would have been helpful to be able to scroll up/down a page through the buffer

### Describe the solution you'd like

I haven't used EasyMotion for years, but with its `easymotion-sn` and `easymotion-tn` you can search for a pattern and, while still in the search prompt, use `Tab` and `S-Tab` to scroll down/up a page and see targets there.

The description of the feature in the EasyMotion repo can be found [here](https://github.com/easymotion/vim-easymotion#n-character-search-motion)

### Describe alternatives you've considered

¯\\_(ツ)_/¯

**Comment by folke** [comment]
You can use the incremental option for this.

**Comment by TxHawks** [comment]
Thanks for the suggestion. I already have `incremental` turned on and `c-g` and `c-t` are nice, but a bit different to what I mean. They jump to the next result, and there could be many in a page. The feature I had in mind is more like a pager (like `c-f` and `c-b`), allowing you to select targets in that page
