### ISSUE TITLE
feature: autojump when only one match even if jump_labels = true in char mode

### ISSUE THREAD

**Issue by xtrats** [folke/flash.nvim#183]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

My char mode config is below, I set `jump_labels = true` so I can decide to jump where I want when there are multiple matches:

```lua
{
  "folke/flash.nvim",
  event = "VeryLazy",
  opts = {
    label = {
      uppercase = false,
    },
    modes = {
      char = {
        jump_labels = true,
        multi_line = false,
        jump = {
          autojump = true,
        },
      },
    },
  },
  -- stylua: ignore
  keys = {
    ...
  },
},
```

for example, in codes below, cursor is before the "s" in "sizeof":

```c++
std::cout << sizeof(DataHdr) << std::endl;
```

There are two situations:

1. If I want to delete the string "sizeof(DataHdr", after I typed `dt)`, then a label ("s" in real case) showed in the place of ")", I had to input `s` to finish the job.

<img width="483" alt="image" src="https://github.com/folke/flash.nvim/assets/5361387/696f7fa9-6bd3-4d78-94f7-a179c78f88e4">

2. If I want to delete the string "sizeof(DataHdr)", after I typed `df)`, then the string ("sizeof(DataHdr)") is select, I had to input `<CR>` to finish the job.

<img width="476" alt="image" src="https://github.com/folke/flash.nvim/assets/5361387/5892addc-1092-4c96-b474-af0f4df8dfd5">

### Describe the solution you'd like

In char mode, when there is only one match, when I typed `dt(` or `df(`, delete the string directly, so there is no another label or `<CR>` needed which is not necessary.

### Describe alternatives you've considered

no alternatives for now, type one more key if no solutions.

**Comment by RayJameson** [comment]
@xtrats hi! what is this gorgeous font you are using?

**Comment by RayJameson** [comment]
> > @xtrats hi! what is this gorgeous font you are using?
> 
> @RayJameson Fire Code (https://github.com/tonsky/FiraCode), I changed some characters to their variants (like 'r').

thanks a lot!

**Comment by mintelm** [comment]
would love this feature too!
