### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by niksingh710** [folke/flash.nvim#184]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.1 Build type: Release LuaJIT 2.1.0-beta3     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/share/nvim"  Run :checkhealth for more info

### Operating system/version

arch linux

### Describe the bug

![image](https://github.com/folke/flash.nvim/assets/60490474/f85788a1-7a8d-44fe-a812-cc459ac3d575)

### Steps To Reproduce

try to save multiple times in any .conf file.

### Expected Behavior

no error should be displayed

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "folke/flash.nvim", opts = {} },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by niksingh710** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/issues/5104

using the repro there was no issue.
but on treesitter they said the error message points to flash

**Comment by max397574** [comment]
this looks like you're trying to use the treesitter functionality from flash inside a file for which you don't have a treesitter
ofc this won't work
can you give exact steps of what you did to get the issues?
all the commands and keys

**Comment by niksingh710** [comment]
i use hyprland so it's config have `.conf` extension
i just open the file and save it nothing happens but if i keep saving it multiple times i get the error.

<c-s> is mapped to `:w!`
i keep pressing that multiple times

**Comment by max397574** [comment]
could you add your mapping to the repro as well?
