### ISSUE TITLE
feature: How to remap the key ';' and ',' when searching to key 'k' and 'i'?

### ISSUE THREAD

**Issue by suncg-sgla** [folke/flash.nvim#185]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

as the question title

### Describe the solution you'd like

i want to remap the keys

### Describe alternatives you've considered

i want to remap the keys

**Comment by folke** [comment]
Please read the docs. It's in there
