### ISSUE TITLE
bug: dot-repeat breaks for `dt/df` motions when moving lines if `multi_line` is false

### ISSUE THREAD

**Issue by norbertkeri** [folke/flash.nvim#189]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

Arch linux

### Describe the bug

If you disable `multi_line`, the dot operator will do nothing after dt/df motions. If you don't disable it, the dot operator works fine.

What's also sightly interesting is that you will have to press "u" 2 times to correctly undo the deletion, I assume the bug also causes an incorrect undo entry.

### Steps To Reproduce

```lua
            require("flash").setup({
                modes = {
                    char = {
                        multi_line = false,
                    }
                }
            })
```

And you have the following text, where | is the cursor:
```
-- |foo,bar,baz
-- foo,bar,baz
```

Press `df,j.`

### Expected Behavior

```
-- bar,baz
-- |bar,baz
```

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
    vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
	"git",
	"clone",
	"--filter=blob:none",
	"https://github.com/folke/lazy.nvim.git",
	lazypath,
    })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
    "folke/tokyonight.nvim",
    { "folke/flash.nvim", opts = {
	modes = {
	    char = {
		multi_line = false
	    }
	}
    }
},
-- add any other plugins here
}
require("lazy").setup(plugins, {
    root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")

-- foo,bar,baz
-- foo,bar,baz
```

**Comment by norbertkeri** [comment]
The bug is still present but I'm ok with closing

**Comment by Kaiser-Yang** [comment]
This issue is still here.

**Comment by Kaiser-Yang** [comment]
#487 should fix this, you can check it.
