### ISSUE TITLE
bug: When pressing S or <C-s> an error appears. 

### ISSUE THREAD

**Issue by nstirnemann7** [folke/flash.nvim#190]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0-dev-2653+g6adfd24a0

### Operating system/version

MacOS 13.4.1

### Describe the bug

When i press the keybidings for S and <C-s> an error appears

{ "S", mode = { "n", "o", "x" }, function() require("flash").treesitter() end, desc = "Flash Treesitter" },
{ "<c-s>", mode = { "c" }, function() require("flash").toggle() end, desc = "Toggle Flash Search" }

The error says : 
E5108: Error executing lua: ...local/share/nvim/lazy/flash.nvim/lua/flash/highlight.lua:203: Invalid 'virt_text_pos'
stack traceback:
        [C]: in function 'nvim_buf_set_extmark'
        ...local/share/nvim/lazy/flash.nvim/lua/flash/highlight.lua:203: in function 'update'
        ...mi/.local/share/nvim/lazy/flash.nvim/lua/flash/state.lua:308: in function '_update'
        ...mi/.local/share/nvim/lazy/flash.nvim/lua/flash/state.lua:248: in function 'update'
        ...mi/.local/share/nvim/lazy/flash.nvim/lua/flash/state.lua:140: in function 'new'
        ...i/.local/share/nvim/lazy/flash.nvim/lua/flash/repeat.lua:51: in function 'get_state'
        ...re/nvim/lazy/flash.nvim/lua/flash/plugins/treesitter.lua:97: in function 'treesitter'
        /Users/batmi/.config/nvim/lua/plugins/movement.lua:8: in function </Users/batmi/.config/nvim/lua/plugins/movement.lua:8>
        
That is when i first press the key S. The everytime i made a movement a different error appears :
Flash error during redraw:
...local/share/nvim/lazy/flash.nvim/lua/flash/highlight.lua:203: Invalid 'virt_text_pos'

The only way for that error to go away, is closing and opening neovim. f,t and s motions works great!

### Steps To Reproduce

Use this config = {
{
  "folke/flash.nvim",
  event = "VeryLazy",
  ---@type Flash.Config
  opts = {},
  -- stylua: ignore
  keys = {
    { "s", mode = { "n", "x", "o" }, function() require("flash").jump() end, desc = "Flash" },
    { "S", mode = { "n", "o", "x" }, function() require("flash").treesitter() end, desc = "Flash Treesitter" },
    { "r", mode = "o", function() require("flash").remote() end, desc = "Remote Flash" },
    { "R", mode = { "o", "x" }, function() require("flash").treesitter_search() end, desc = "Treesitter Search" },
    { "<c-s>", mode = { "c" }, function() require("flash").toggle() end, desc = "Toggle Flash Search" },
  },
}
}

### Expected Behavior

That flash works normally.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
  "folke/flash.nvim",
  event = "VeryLazy",
  ---@type Flash.Config
  opts = {},
  -- stylua: ignore
  keys = {
    { "s", mode = { "n", "x", "o" }, function() require("flash").jump() end, desc = "Flash" },
    { "S", mode = { "n", "o", "x" }, function() require("flash").treesitter() end, desc = "Flash Treesitter" },
    { "r", mode = "o", function() require("flash").remote() end, desc = "Remote Flash" },
    { "R", mode = { "o", "x" }, function() require("flash").treesitter_search() end, desc = "Treesitter Search" },
    { "<c-s>", mode = { "c" }, function() require("flash").toggle() end, desc = "Toggle Flash Search" },
  },
},
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- This are my options
-- Set highlight on search
vim.o.hlsearch = false

-- Make line numbers default
vim.wo.relativenumber = true

-- Enable mouse mode
vim.o.mouse = 'a'

-- Sync clipboard between OS and Neovim.
--  Remove this option if you want your OS clipboard to remain independent.
--  See `:help 'clipboard'`
vim.o.clipboard = 'unnamedplus'

-- Enable break indent
vim.o.breakindent = true

-- Save undo history
vim.o.undofile = true

-- Case-insensitive searching UNLESS \C or capital in search
vim.o.ignorecase = true
vim.o.smartcase = true

-- Keep signcolumn on by default
vim.wo.signcolumn = 'yes'

-- Decrease update time
vim.o.updatetime = 250
vim.o.timeoutlen = 300

-- Set completeopt to have a better completion experience
vim.o.completeopt = 'menuone,noselect'

vim.o.termguicolors = true

vim.o.sessionoptions="blank,buffers,curdir,folds,help,tabpages,winsize,winpos,terminal,localoptions"

vim.opt.autoindent = true
vim.opt.expandtab = true
vim.opt.shiftwidth = 2
vim.opt.tabstop = 2


vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
You are using an outdated nightly. Either use Neovim stable or a recent nightly

**Comment by nstirnemann7** [comment]
Thank you so much! Can I make a PR to change the readme to specify that? So other people dont get stuck in the same error?
