### ISSUE TITLE
feature: vim-columnmove inside flash.nvim

### ISSUE THREAD

**Issue by simonmandlik** [folke/flash.nvim#196]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

 It would be really nice if flash.nvim would also offer functionality similar to [vim-columnmove](https://github.com/machakann/vim-columnmove), that is, column-wise f, t, F, and T motions.

### Describe the solution you'd like

Neovim alternative of [vim-columnmove](https://github.com/machakann/vim-columnmove)

### Describe alternatives you've considered

[vim-columnmove](https://github.com/machakann/vim-columnmove) works perfectly fine in neovim as it is, this is just a feature suggestion.

**Comment by folke** [comment]
not interested in adding this
