### ISSUE TITLE
Error when setting up 2-char jump

### ISSUE THREAD

**Issue by Neur1n** [folke/flash.nvim#199]
I'm following the example in README.md to set up 2-char jump, but there is an error which is caused by the following code:
https://github.com/folke/flash.nvim/blob/967117690bd677cb7b6a87f0bc0077d2c0be3a27/lua/flash/search/init.lua#L48

When NeoVim starts up, `local line` is `nil` since `vim.api.nvim_buf_get_lines` returns an empty table. Please checkout this [comment](https://github.com/folke/flash.nvim/issues/120#issuecomment-1663559912) for more details.

Is this a bug or am I loading flash.nvim incorrectly (using vim-plug)? Your help will be much appreciated.

**Comment by IndianBoy42** [comment]
I think you are loading flash.nvim incorrectly, specifically setting up the keymap incorrectly. Because there is no reason for that line (or the function containing it) to be called on startup (ie when buf_get_lines would return an empty table)

**Comment by Neur1n** [comment]
You are correct. My keymap was missing `function() ... end` or `<cmd> ... <cr>`. Thanks!
