### ISSUE TITLE
How to start the plugin without having to press the "s" key?

### ISSUE THREAD

**Issue by 7c78** [folke/flash.nvim#201]
If I am not mistaken, I have to press the `s` key to enhance my `/` key. `s` only allows me to search within the screen, while `/` the whole document, so I only press `s` once and then use `/` exclusively afterward. Is there anyway to start the plugin without having to press `s`?

**Comment by IndianBoy42** [comment]
You have setup flash.nvim to be lazyloaded on "s" key press. Check the lazy.nvim docs for other lazy loading triggers, such as `event`, or just don't lazy load. Adding `/` to the `keys` table in the lazy spec could work as well

**Comment by 7c78** [comment]
@IndianBoy42 thanks for the response. I read flash's readme and see that to start the plugin, I need to run `require("flash").jump()`. How can I achieve that with lazy's loading triggers? And I do not want to map `/` to `require("flash").jump()`, because I want to search in the whole document.

**Comment by UTFeight** [comment]
@7c78 

Read the Lazy.nvim docs

If you are new to programming or neovim, It's an essential habit to get used to reading docs because you are going to find few people helping you.
