### ISSUE TITLE
bug: The plugin doesn't work properly in the latest version of vscode-neovim.

### ISSUE THREAD

**Issue by shininome** [folke/flash.nvim#208]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

Macos 13.5

### Describe the bug

I noticed that the speed is very slow when I use the "s" search function. After investigation, I confirmed that it is caused by the upgrade of vscode-neovim.

### Steps To Reproduce

1. enable flash and use neovim-vscode 0.4.1,its become so solwly
2. use vscode - neovim 0.3.2 its became normal

### Expected Behavior

I hope it can be adapted to the latest version

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "folke/flash.nvim", opts = {} },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by edicon** [comment]
I also have the same problem

**Comment by jellydn** [comment]
That's known issue/bug on https://github.com/vscode-neovim/vscode-neovim/issues/1349#issuecomment-1671923558 FYI

**Comment by theol0403** [comment]
Fixed
