### ISSUE TITLE
New Feature: linewise jump motions

### ISSUE THREAD

**Issue by kevintraver** [folke/flash.nvim#213]
Using the following for **_jump to line_**
```
keys = {
  {
    "\", -- keybinding
    mode = { "o" },
    function()
      require("flash").jump({
        search = { mode = "search", max_length = 0 },
        label = { after = { 0, 0 } },
        pattern = "^",
      })
    end,
    desc = "Flash (jump to line)",
  },
}
 ```
given this example (the jump to line keymap is `\`)

```
myFunction (abc)
  
  customMethod(in*put) <-- cursor is at *
  
  text
  moreText
  
  anotherCustomMethod <-- want to delete to here including this line

end
```

if if I enter _jump to line_ in operator pending (delete) `d\`
```
myFunction (abc)
s 
d customMethod(in*put) <-- cursor is at *
f 
g text
h moreText
j 
k anotherCustomMethod <-- want to delete to here including this line
l
qnd
```

and then press `k`

the result is the following

```
myFunction (abc)
  
  customMethod(in anotherCustomMethod <-- delete happened, but characterwise

end
```

### Describe the solution you'd like

Proposed solution:

a new jump to motion that operates **_linewise_**

```
myFunction (abc)
  
  customMethod(in*put) <-- cursor is at *
  
  text
  moreText
  
  anotherCustomMethod <-- want to delete to here including this line

end
```

if if I enter _jump to line_ in the **new** operator pending *linewise* (delete) `d\`

```
myFunction (abc)
s 
d customMethod(in*put) <-- cursor is at *
f 
g text
h moreText
j 
k anotherCustomMethod <-- want to delete to here including this line
l
qnd
```

and then press `k`

the result would be the following:

```
myFunction (abc)
  

end
```

### Describe alternatives you've considered

This can currently be done in _visual-line_ mode:

```
myFunction (abc)
  
  customMethod(in*put) <-- cursor is at *
  
  text
  moreText
  
  anotherCustomMethod <-- want to delete to here including this line

end
```

enter _visual line-wise_ mode `V` and then **_press jump to line_** `\`

```
myFunction (abc)
s 
d customMethod(in*put) <-- cursor is at * (entire line is highlighted)
f 
g text
h moreText
j 
k anotherCustomMethod <-- want to delete to here including this line
l
qnd
```

and then press `k`

Now you have the updated selection

```
myFunction (abc)
  
  customMethod(in*put) <-- selection
                       <-- selection
  text                 <-- selection
  moreText             <-- selection
                       <-- selection  
  anotherCustomMethod  <-- selection

end
```

then press `d`

the result is the following:

```
myFunction (abc)
  

end
```

This works, but the new mode would be more efficient and you wouldn't have to enter visual line-wise mode.

**Comment by IndianBoy42** [comment]
You can actually do `<operator>V<motion>` to force linewise operation, for any existing motion. (:h o_V)

You could probably make a mapping using that 

Or look into overriding the `action` callback to select it linewise
