### ISSUE TITLE
feature: jump to start/end of any visible TS node

### ISSUE THREAD

**Issue by JosefLitos** [folke/flash.nvim#216]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

Current `treesitter` mode can jump to start or end, but the position must be decided beforehand.

Also, it would be nice to jump to deeper nodes from the current one, not just go upwards in the tree.

### Describe the solution you'd like

Offer a `treesitter_jump` mode, which would operate on the following basis:
- different label for end or start of a node - or select a node and then select to go to start or end
- all visible nodes would be jumpable, not just upwards through the tree
- a possibility to filter node types (operator, name/value...)

### Describe alternatives you've considered

I couldn't get `treesitter_search` to not be in `range` selection but just on end or start.

<kbd>I</kbd> on selection doesn't move to beginning of selection but beginning of line when selection is just part of a single line, though that is fixable by `vim.keymap.set("v", "I", "o<Esc>i")`.

Using `treesitter_search` with <kbd>space</kbd> can highlight all nodes, but cannot filter them.

**Comment by IndianBoy42** [comment]
I think you can try adapting the treesitter_search matcher to create labels at the start and end of the nodes. 
https://github.com/folke/flash.nvim/blob/967117690bd677cb7b6a87f0bc0077d2c0be3a27/lua/flash/plugins/treesitter.lua#L140

all visible nodes being labelled is unlikely to work, there are just too many nodes, you need the search to prefilter like treesitter_search does.

**Comment by JosefLitos** [comment]
You're right. I was sure what I thought of already exited, so I kept trying to find a way to make it work like I wanted and indeed almost did.

I think in the end the only feature I mentioned, but didn't find a way to use is the treesitter node type filtering - `nvim-treesitter-textobjects` does basically that, but doesn't allow simpler jumping in between. On the other hand, filtering for bigger blocks also doesn't make much sense, because the majority of the blocks won't fit into the screen -> I'm going to try `nvim-navbuddy` for that feature.
