### ISSUE TITLE
feature: Mode-specific highlight groups

### ISSUE THREAD

**Issue by simonmandlik** [folke/flash.nvim#217]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

It would be nice to have different highlight groups for each of the modes.

For example, for `jump` I'm using backdrop, whereas for fFtT movement I'm not. When backdrop is off, I want labels to have greyish background so that they are visible on top of syntax highlighting. On the other hand, when backdrop is on, everything is greyish, so I would like to use some color.

### Describe the solution you'd like

Define new highlight groups like 

`FlashJumpLabel`, `FlashFLabel`
`FlashJumpBackdrop`, `FlashFBackdrop`, etc.

linked by default to the original groups.

### Describe alternatives you've considered

Currently, I'm using one highlight group for all modes, which seems suboptimal, see above

**Comment by IndianBoy42** [comment]
Can't you already customize `opts.highlight.groups` by mode?

**Comment by folke** [comment]
this is already possible as @IndianBoy42 pointed out
