### ISSUE TITLE
bug: Weird order of TS nodes when expanding with ; and ,

### ISSUE THREAD

**Issue by simonmandlik** [folke/flash.nvim#219]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

MacOS 13.4.1

### Describe the bug

Using the following test code

```cpp
int main() {
        for (int i = 0; i < 10; ++i) {
                i += 1;
        }
}
```

starting from "i" in `i < 10` by pressing `S` and then `;`, the following gets selected.

1. just `i`
<img width="389" alt="image" src="https://github.com/folke/flash.nvim/assets/16707112/ab2656f6-1ab2-4747-a2cc-e92f2c90e03b">

2. whole `for` loop
<img width="389" alt="image" src="https://github.com/folke/flash.nvim/assets/16707112/8b451e30-076f-4fe4-8d3a-b36d4e8fe95b">

3. function "block"
<img width="389" alt="image" src="https://github.com/folke/flash.nvim/assets/16707112/0b659833-bb82-45b4-a0f8-606aae13d0e4">

4. everything
<img width="389" alt="image" src="https://github.com/folke/flash.nvim/assets/16707112/2e7fb9e1-af82-4c07-b1f2-3182353a4cf9">

5. function "block" (again)
<img width="389" alt="image" src="https://github.com/folke/flash.nvim/assets/16707112/2c529701-a7fb-44f5-91df-39eee3b6e4ea">

6. comparison `i < 10` 
<img width="389" alt="image" src="https://github.com/folke/flash.nvim/assets/16707112/a59e0fe3-3ab2-4d20-868a-84117c3df6a2">

7. `i` again, looping from the beginning

### Steps To Reproduce

1. `nvim -u repro.lua test.cpp`
2. Insert
```cpp
int main() {
        for (int i = 0; i < 10; ++i) {
                i += 1;
        }
}
```
3. Position the cursor on "i" in `i < 10`
4. Press `S`, and then repeatedly `;`

### Expected Behavior

I would expect the order 1) 6) 2) 3) 4),

which is happening when using incremental selection from `nvim-treesitter`.

### Repro

```Lua
local root = vim.fn.fnamemodify("./.repro", ":p")
for _, name in ipairs({ "config", "data", "state", "cache" }) do
    vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

local plugins = {
    {
        "folke/flash.nvim",
        keys = {
            { "S", mode = { "n", "o", "x" }, function() require("flash").treesitter() end},
        },
    },
    {
        "nvim-treesitter/nvim-treesitter",
        build = ":TSUpdate",
        config = function ()
            require("nvim-treesitter.configs").setup {
                ensure_installed = { "cpp" },
                incremental_selection = {
                    enable = true,
                    keymaps = {
                        init_selection = "gnn",
                        node_incremental = "grn",
                        scope_incremental = "grc",
                        node_decremental = "grm",
                    },
                },
            }
        end
    }
}

require("lazy").setup(plugins, {
    root = root .. "/plugins",
})

vim.cmd[[set termguicolors]]
```

**Comment by folke** [comment]
Sorry for the delay. Fixed!
