### ISSUE TITLE
feature: support remote flash from insert mode

### ISSUE THREAD

**Issue by jtackaberry** [folke/flash.nvim#222]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

As you know, C-o in insert mode allows performing a single normal mode command and then returns to insert mode.  When using this to perform a remote flash (`<C-o>yr`) however, the following gets inserted into the buffer instead:

```
call v:lua.cmp.utils.feedkeys.call.run(6)
```

### Describe the solution you'd like

Ideally, from insert mode `<C-o>yr` would work as in normal mode, permitting the flash/yank and returning back to insert mode, at which point I can paste using `<C-r>0` (or whatever register I happened to perform the remote yank into).

### Describe alternatives you've considered

Just exiting back to normal mode and performing the remote flash as usual.

**Comment by gsiddhant159** [comment]
I would still like to see this implemented
