### ISSUE TITLE
bug: Folds between source and target aren't preserved after jumping

### ISSUE THREAD

**Issue by MariaSolOs** [folke/flash.nvim#224]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0-dev-979+g794981d9b

### Operating system/version

Mac Ventura 13.5

### Describe the bug

After `flash`-jumping, all folds in the current buffer (between the jumping position and the target) are opened.

### Steps To Reproduce

1. Use the configuration provided below in `repro.lua`.
2. Create a file called `bug.lua` with the following content:
```lua
--Folke is my idol and I know he will fix this bug.
--{{{
local folded = {
  1,
  2,
  3,
  4,
}
--}}}

local target = 0
```
3. Open the file above with `nvim -u repro.lua bug.lua`. Using the settings below, the code surrounding `folded` should be (surprise!) folded. 
4. Make sure the cursor is in position 1:1 and `flash`-jump to `target` (I created the respective mapping using `'s'`). 
5. Notice how the folded region is unfolded, despite the initial position and the destination being in unfolded places :(

FWIW `flash` won't open the folds in the following scenarios (assuming that the jumping position is still the `F` in `Folke` and the target is `target`):
```lua
--{{{
local folded = {
  1,
  2,
  3,
  4,
}
--}}}

--Folke is my idol and I know he will fix this bug.
local target = 0
```
```lua
--Folke is my idol and I know he will fix this bug.
local target = 0

--{{{
local folded = {
  1,
  2,
  3,
  4,
}
--}}}
```
And so I imagine this is because of how `flash` (or `neovim`?) computes the line/column of the destination and needs to open folds for that. I do find it a bit annoying and so I would _love_ ®️ a solution for this. 

### Expected Behavior

For ALL folds to be preserved when jumping. I can tolerate unfolds if the target is in a folded line, but if the target and the current position are not inside a fold, I would love for the remaining folded places to remain unaffected. 

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "folke/flash.nvim",
    opts = {},
    keys = {
      {
        "s",
        mode = { "n", "x", "o" },
        function()
          require("flash").jump()
        end,
        desc = "Flash",
      },
    },
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")

-- add anything else here
vim.wo.foldmethod = "marker"
```

**Comment by mivort** [comment]
Interestingly, folds are kept intact if simple custom action is used, e.g.:
``` lua
require("flash").jump({
  action = function(match) vim.api.nvim_win_set_cursor(match.win, match.pos) end,
})
```
So defining own custom action can be used as workaround, and the issue probably lies somewhere in the default one.

**Comment by MariaSolOs** [comment]
Thanks for the workaround @mivort! 
My concern though is that the default `jump` action does have some important logic (dealing with jumping to other windows, etc) that I don't want to monkey-patch. 

Looking at the implementation of `open_folds` and #39, maybe that folding behaviour could be configurable? I find it really odd to `flash`-jump to a position if I cannot see it (if the target is inside a folded region). I'm not interested in such a functionality, but instead I would like to keep the current fold state when jumping in the unfolded code.

WDYT @folke? ;)

**Comment by mivort** [comment]
I think it would be nice if the unfolding can be made optional, as this operation may be a bit CPU intensive in case of big files (since it has to iterate over each line and check for folds), and even if it will unfold only the folded target (as your fix does), it still can accidentally mess up currently folded stuff (in case of wrong jump) without a quick way to undo it.

Anyway, I kinda liked the way of defining own custom lightweight purpose-driven actions for specific operations :) It's really cool to have this library-like flexibility which flash.nvim architecture provides.

> EDIT: Okay I have a suggested fix: https://github.com/folke/flash.nvim/pull/225

There may be still a bit of a counter-intuitive behaviour in case when target is folded: it will open all the folds on a way to the target, not only the target.

**Comment by MariaSolOs** [comment]
@mivort those are good points. Maybe separating the actions into isolated customizable steps would satisfy everyone. For now I think that my suggested modification isn't intrusive with the current implementation, but your idea does sound like a good long term solution :)
