### ISSUE TITLE
i like your symbol in c section setting in statusline!

### ISSUE THREAD

**Issue by Mr-LLLLL** [folke/flash.nvim#227]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

i like your c section setting  in statusline. could you tell me what plugin? i search a lot plug, just find some winbar plugin, but i don't like show synbol in winbar.

### Describe the solution you'd like

thanks

### Describe alternatives you've considered

thanks

**Comment by max397574** [comment]
this is most likely from lazyvim config
and discussions exists for questions unrelated to the plugin like this

**Comment by Mr-LLLLL** [comment]
ok, i found a plug, navic is good for this functiom thanks
