### ISSUE TITLE
feature: highlights specific highlight group for Cursor

### ISSUE THREAD

**Issue by grota** [folke/flash.nvim#228]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

Using f,F,t,T I cannot see very well my current cursor position.
As far as I can see I would be able to do that only by setting nvim's "Cursor" highlight (which I'd rather not since it affects the colors in other places).

### Describe the solution you'd like

A new highlight group (linked to Cursor for backwards compatibility) used here https://github.com/folke/flash.nvim/blob/8a8e74922a383c253b7f92e042b749150140c8d1/lua/flash/highlight.lua#L72

### Describe alternatives you've considered

changing hl Cursor, too invasive

**Comment by max397574** [comment]
well if you don't want to change cursor highlight why not change the other ones so they are different from cursor?
can't test this right now since I'm not at my computer but I'm quite sure this is possible

**Comment by grota** [comment]
Yeah, that's what I'm going for right now: setting `FlashLabel`, `FlashMatch` and `FlashCurrent`.  
But it's kind of a workaround IMHO.

**Comment by max397574** [comment]
no not at all
you want something to be different from cursor but don't want to change cursor you have to change the other highlights

**Comment by grota** [comment]
You mean to change the other highlights of my colorscheme, in general, so that flash.nvim defaults stand out more?
If so, sure it's doable, but I guess it's even more roundabout (for context, I'm using catppucin and I am almost happy by disabling its builtin integration with flash and overriding `FlashLabel`, `FlashMatch` and `FlashCurrent`, but I'd rather just have the extmark use an additional custom hl group.

@folke I could probably start working on a PR to add this feature, would you consider it?

**Comment by Boomslet** [comment]
I'm in the same situation and happy to contribute to get this in
