### ISSUE TITLE
Is that possible to install with paq?

### ISSUE THREAD

**Issue by Twix53791** [folke/flash.nvim#229]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

Last version

### Operating system/version

Arch last upgrade

### Describe the bug

Hi, I am new on vim trying to setup it. I probably dont understand how manage things between vim and lua plugins, but I can't make flash to work. I am trying to install it via paq (I don't want to use Lazy, I want a lightweight plugin manager like vim plug). Paq install it well, but the keybindings are not working, nothing happens...
 Here the code I wrote:
```lua
require "paq" {
{
  "folke/flash.nvim",
  opts = {},
  keys = {
    { "s", mode = { "n", "o", "x" }, function() require("flash").jump() end, desc = "Flash" },
    { "S", mode = { "n", "o", "x" }, function() require("flash").treesitter() end, desc = "Flash Treesitter" },
    { "r", mode = "o", function() require("flash").remote() end, desc = "Remote Flash" },
    { "R", mode = { "o", "x" }, function() require("flash").treesitter_search() end, desc = "Treesitter Search" },
    { "<c-s>", mode = { "c" }, function() require("flash").toggle() end, desc = "Toggle Flash Search" },
  }
}
}
```
I have installed treesitter of course. Thanks to any clues!

### Steps To Reproduce

Write the code above in init.lua

### Expected Behavior

I would like just to activate it...

### Repro

```Lua
require "paq" {
    "savq/paq-nvim", -- Let Paq manage itself

    { 'nvim-treesitter/nvim-treesitter' },

{ "folke/flash.nvim",
  opts = {},
  keys = {
    { "s", mode = { "n", "o", "x" }, function() require("flash").jump() end, desc = "Flash" },
    { "S", mode = { "n", "o", "x" }, function() require("flash").treesitter() end, desc = "Flash Treesitter" },
    { "r", mode = "o", function() require("flash").remote() end, desc = "Remote Flash" },
    { "R", mode = { "o", "x" }, function() require("flash").treesitter_search() end, desc = "Treesitter Search" },
    { "<c-s>", mode = { "c" }, function() require("flash").toggle() end, desc = "Toggle Flash Search" },
  }
}

}
```

**Comment by max397574** [comment]
well that `keys` table is lazy.nvim specific
you just have to define the keybindings yourself
and the `opts={}` makes lazy call the setup function. With paq you have to do that yourself as well then

**Comment by Twix53791** [comment]
Ah! OK, thanks! Calling the setup function, I see, about the bindings, what is the syntax ? I guess it is not something like `map key <Plug>Command` ? That 's the thing which muddles me : many plugins comes with commands I can run in the command prompt or link to keys in init.vim, for example Telescope. It is not the case with this plugin? 
Or maybe, I saw for telescope I can use lua function like that `nnoremap <leader>ff <cmd>lua require('telescope.builtin').find_files()<cr>`, maybe it is the way to bind the flash plugin functions like : `<cm>lua require("flash").jump()<cr>` ??

**Comment by max397574** [comment]
just use lua keybindings
`vim.keymap.set({"n","o","x"},"s",function()...end,{desc="Flash"})`

**Comment by Twix53791** [comment]
Thank you very much @max397574, it works! I am glad because it is a nice plugin, I like the fact than the all page is grayed out when jumping, usefull to focus on the target and distinguishing the labels.
Anyway, at the end, I set up my vim with vim-plug. Simple and efficient. I post here the full code to help people after me:

## Install with [vim-plug](https://github.com/junegunn/vim-plug)

In init.vim:
```vim
...
Plug 'folke/flash.nvim'
...
call plug#end()
...
source ~/.config/nvim/plugrc/flashrc.vim
```

In the file named here flashrc.vim:
```vim
lua << EOF
    require('flash').setup{
        search = {
            mode = function(str)
              return "\\<" .. str
            end
        },
        jump = {
            autojump = true,
        },
        label = {
            rainbow = {
              enabled = true,
              shade = 9,
            }
        }
    }

    vim.keymap.set({"n","o","x"},"j", function() require("flash").jump() end, {desc="Flash"})
    vim.keymap.set({"i"}, "<C-j>", function() require("flash").jump() end, {desc="Flash"})

EOF
```
