### ISSUE TITLE
How to use different options in Operator Mode based on forward/backward?

### ISSUE THREAD

**Issue by singlexyz** [folke/flash.nvim#232]
I have this mapping, it works like `dt` when jump forward.
```lua
{
  "s",
  mode = { "o" },
  function() require("flash").jump({ jump = { offset = -1 } }) end,
}
```
But when jump backward, I hope it works like `dF`.

Is there a way to make a judgment?

**Comment by IndianBoy42** [comment]
maybe override the action callback and adjust the target based on whether its before or after

**Comment by singlexyz** [comment]
I figure out:
```lua
require("flash").jump({ jump = { inclusive = false } })
```
