### ISSUE TITLE
bug: Cannot repeat f F t T motions when remapping the key and enabled jump_labels

### ISSUE THREAD

**Issue by Verf** [folke/flash.nvim#237]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0-dev-1055+gb7734c4ec

### Operating system/version

Windows 10

### Describe the bug

I'm a [Norman Keyboard Layout](https://normanlayout.info/index.html) user so I map the `f` `F` `t` `T` to `t` `T` `k` `K`. These maps worked well when I disabled the jump_labels option. But if I enabled jump_labels, I cannot repeat motions by mapped key. For example, when I press `t{char}` and I want to repeat this motion. I can press `t` to repeat the motion, but if I enabled jump_labels, I must press `f` to repeat the motion.

### Steps To Reproduce

1. map keys and enable jump_labels
```lua
opts = {
    modes = {
        char = {
            jump_labels = true,
            keys = {
                f = 't',
                F = 'T',
                t = 'k',
                T = 'K',
            },
        },
    },
},
```
2. `t{char}` and then repeat

### Expected Behavior

Repeat using mapped keys.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	"folke/tokyonight.nvim",
	{
		"folke/flash.nvim",
		event = 'VeryLazy',
		opts = {
			modes = {
				char = {
					jump_labels = true,
					keys = {
						f = "t",
						F = "T",
						t = "k",
						T = "K",
					},
				},
			},
		},
	},
	-- add any other plugins here
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by jensenojs** [comment]
+1
