### ISSUE TITLE
feature: when tressitter range is trigger, auto select minimum range and don't add label in selected range

### ISSUE THREAD

**Issue by Mr-LLLLL** [folke/flash.nvim#239]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

when i use S trigger treesitter, then will auto selected minimun range, and same add label for outer range. i think the selected range label maybe not show is better.(cause mininum is selected for default, label will do nothing)

### Describe the solution you'd like

don't add label on selected

### Describe alternatives you've considered

only skip first label

### Additional context

i try to resolve this issue, if i have space time, but i am buzy for now.if don't anybody solve this, i will submit a PR in later

**Comment by IndianBoy42** [comment]
Doesn't the config option `opts.label.current` already solve this?

**Comment by Mr-LLLLL** [comment]
> Doesn't the config option `opts.label.current` already solve this?

where to set? i can't see it in document

**Comment by Mr-LLLLL** [comment]
yes, i see it, but not solve my proble.
the `opt.label.current` is can't label on first match in jump or search, but not affect treesitter, mayby is a bug?

**Comment by Mr-LLLLL** [comment]
and i think treesiter behavior is not like jump or search.
treesiter will selected a range, so don't label on first match is goods way. cause first match is be selected, key label, will do nothing.

**Comment by IndianBoy42** [comment]
it doesn't do nothing right? it ends the flash mode

**Comment by Mr-LLLLL** [comment]
> it doesn't do nothing right? it ends the flash mode

yes,you are right, it ends the flash mode. but end flash mode can be `<esc>`.
if i have selected range in trigger flash treesitter, and first matched is my target, i will direct execute other operation like `d`, `y` ...

**Comment by Mr-LLLLL** [comment]
`;,` is cool feature,but i don't konw. then  i think you are right; i agree your said

> maybe it can be configurable but I think just labelling the first selection so the flow is consistent makes more sense. especially as the label key will probably be closer to the home position than esc.
> 
> you can already (in flash treesitter visual mode) execute an operation with the initial selected range or the incrementally selected range (using `;,`) assuming there is no label with the key for the operation, which is configurable
