### ISSUE TITLE
feature: vscode-neovim now supports cross-window motions

### ISSUE THREAD

**Issue by theol0403** [folke/flash.nvim#243]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

https://github.com/vscode-neovim/vscode-neovim/pull/1417

### Describe the solution you'd like

Remove disabling cross-window motions from the vscode defaults.

Also, highlight groups now work out of the box - it would be worth investigating to see if you don't need to provide any custom logic for vscode.

### Describe alternatives you've considered

N/A

**Comment by IndianBoy42** [comment]
#230 already, folke is on vacation
