### ISSUE TITLE
feature: allow disabling clever-f style repeat keymaps

### ISSUE THREAD

**Issue by samjwill** [folke/flash.nvim#245]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

Thanks for the wonderful plugin folke! It's quality as always. I've been enjoying it a lot.

#### The problem I've run into:
I am unable to determine a way to disable clever-f style repeat motions whilst retaining the additional functionality that this plugin provides for the `F`/`f`/`T`/`t` motions (i.e. highlighting matching letters and working across multiple lines).

`;`, and `,` are baked into my muscle memory for going forward/backwards to the next/previous matching letter. As such, if I, for example, start a motion with `f` + a letter, when pressing `f` a second time, I would like to be able to start a new motion instead of repeating the old one.

### Describe the solution you'd like

It would be awesome if there was a configuration option that could be provided to the setup function which would disable the clever-f style repeat motions, allowing `F`/`f`/`T`/`t` to start a new motion every time they're pressed.

### Describe alternatives you've considered

I have tried playing around with the `char_actions` function (located in `modes` -> `char` -> `char_actions`) to see if I could come up with some way to initiate a new motion by re-assigning `[motion:lower()]` and `[motion:upper()]`, but unfortunately, have not had any luck in getting something functional that resembles what I'm trying to achieve.

I think it may be possible that the desired functionality can be replicated by binding them to a customized `require("flash").jump(...)` call, but I'm not 100% certain. Setting both to `nil`, still results in subsequent presses of `f` moving forward to the next match.

### Additional context

Apologies if there is already a simple way to do this. Feel free to close the issue if so!

**Comment by rockneverdies55** [comment]
Totally agree with this idea. After i press the target letter, flash should exit immediately. I can move back and forth with ; and , anways. If i press f again, perhaps i want to start a new f move.

**Comment by max397574** [comment]
`modes.char.enabled=false` should do the job, just look at the default config in the readme

**Comment by samjwill** [comment]
> modes.char.enabled=false should do the job, just look at the default config in the readme

Correct me if I'm wrong, but that disables it entirely, no? I would like to preserve the functionality that allows the motions to extend across multiple lines and highlight matching letters.

**Comment by max397574** [comment]
then perhaps the autohide option?

**Comment by samjwill** [comment]
> then perhaps the autohide option?

I don't believe that option has any effect as per #231.

Plus, I'm not sure that it would do what I'm describing anyway.

**Comment by folke** [comment]
Just pushed a fix for this.

You still need to override:

```lua
      modes = {
        char = {
          char_actions = function()
            return {
              [";"] = "next", -- set to `right` to always go right
              [","] = "prev", -- set to `left` to always go left
            }
          end,
        },
```
