### ISSUE TITLE
bug: jump back(c-o) not work as expected

### ISSUE THREAD

**Issue by yimingwangdell** [folke/flash.nvim#247]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

10

### Operating system/version

manjaro

### Describe the bug

origin->A->origin(c-o)->B->A(c-o)

what I expected:  jump back to origin not A, because I jump to B from origin, c-o should bring me to origin.

### Steps To Reproduce

as descripted.

### Expected Behavior

jump back to where I am from.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "folke/flash.nvim", opts = {} },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Can you please be clearer what doesnt work? Provide every step including what flash commands you use.
Also see the `jumplist` option

**Comment by yimingwangdell** [comment]
@folke need more tests about which plugin is affecting the <C-O>, sometimes <C-O> doesn't even bring me back to previous position before flash jump.
