### ISSUE TITLE
feature: Option to disable search integration

### ISSUE THREAD

**Issue by tw1t611** [folke/flash.nvim#249]
### Did you check the docs?

- [x] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

I like the way you integrate with other neovim tools, but it would be nice to have the option to disable that behaviour.

### Describe the solution you'd like

Options to disable certain integrations like

```lua
opts = {
  search = false,
  multi_window = false,
}
```

### Describe alternatives you've considered

I don't consider other options. Flash seems to be the superior nvim motion plugin. :)

**Comment by folke** [comment]
You can already do all of that. Please read the docs

**Comment by tw1t611** [comment]
It might wasn't clear.

I can disable a search direction.

```lua
opts = {
  search = {
    forward = false,
    wrap = false,
    multi_window = false,
  }
}

I can't disable the plugin on search using slash, while still using the hotkey e.g. <leader s>.

**Comment by folke** [comment]
![image](https://github.com/folke/flash.nvim/assets/292349/7560a79d-239d-42f3-b236-65a531127996)

**Comment by tw1t611** [comment]
Haven't seen this, sorry.
For everyone coming across this issue, this is my final config:

```lua
-- flash: disable multi window, plugin on / and ?
{
  "folke/flash.nvim",
  event = "VeryLazy",
  ---@type Flash.Config
  opts = {
    search = {
      multi_window = false,
     },
    modes = {
      search = {
        enabled = false,
      },
    },
  },
},
```
