### ISSUE TITLE
bug: Colors issue

### ISSUE THREAD

**Issue by kobzar** [folke/flash.nvim#252]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.2

### Operating system/version

Any

### Describe the bug

I am use Material color theme 
https://github.com/marko-cerovac/material.nvim
And something wrong with my high colors by default. 
Its look is terrible for use. 
<img width="1277" alt="image" src="https://github.com/folke/flash.nvim/assets/1912842/512280ab-e859-4647-a9a6-9c0284beb3dc">

Could you advice hot to make it user friendly?

### Steps To Reproduce

Just run

### Expected Behavior

```Lua
return {
  {
    "folke/flash.nvim",
    event = "VeryLazy",
    ---@type Flash.Config
    opts = {

      modes = {
        char = {
          jump_labels = false,
          highlight = {
            backdrop = true,
            groups = {
              match = "Blue",
              label = "Red",
            },
          },
        },
      },
    },
  -- stylua: ignore
  keys = {
    { "s", mode = { "n", "x", "o" }, function() require("flash").jump() end, desc = "Flash" },
    { "S", mode = { "n", "x", "o" }, function() require("flash").treesitter() end, desc = "Flash Treesitter" },
    { "r", mode = "o", function() require("flash").remote() end, desc = "Remote Flash" },
    { "R", mode = { "o", "x" }, function() require("flash").treesitter_search() end, desc = "Treesitter Search" },
    -- { "<c-s>", mode = { "c" }, function() require("flash").toggle() end, desc = "Toggle Flash Search" },
  },
  },
}
```

**Comment by kobzar** [comment]
Ohh sorry
I find the same issue on Material theme repo
https://github.com/marko-cerovac/material.nvim/issues/171

**Comment by folke** [comment]
Yeah, the theme needs to be fixed, or you can do it manually. 
The hl groups are mentioned in the readme
