### ISSUE TITLE
bug: `label.exclude` doesn't work

### ISSUE THREAD

**Issue by Pagliacii** [folke/flash.nvim#253]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0-dev-1031+gc431d820e

### Operating system/version

Windows 11

### Describe the bug

I don't want to use `p` to as a jump label, so I add it to the `label.exclude` option, but this doesn't work.

![image](https://github.com/folke/flash.nvim/assets/12871143/90e07c54-7d1c-41ff-98eb-fbc4f6feede4)

### Steps To Reproduce

1. set `label.exclude` to `"p"`.
2. open neovim and hit `f` key to find a character.
3. the `p` still is a label.

### Expected Behavior

The `p` isn't a jump label after setting the `label.exclude` option.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
    "folke/tokyonight.nvim",
	{
		"folke/flash.nvim",
		opts = {
			label = {
				exclude = "p",
				rainbow = {
					enabled = true,
				},
			},
			modes = {
				char = {
					jump_labels = true,
				},
			},
		},
	},
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
char mode already excludes some labels, so you will need to override it there.
`opts.mode.char.label.exclude`.

You can find the defaults in the readme/config section

**Comment by Pagliacii** [comment]
Thanks, it works now
