### ISSUE TITLE
feature: search display label when <Cr> typed

### ISSUE THREAD

**Issue by zhaoxuyll** [folke/flash.nvim#254]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

When search mode is enabled, labels are displayed immediately, preventing the full entry of criteria that contain labels in the search. For example, when typing "use", the r tag appears, and when you type r again, you perform a jump instead of continuing to enter the search condition "username".

### Describe the solution you'd like

Expect to add functionality and display labels when entered<Enter>.

### Describe alternatives you've considered

No

**Comment by max397574** [comment]
you should read the docs
search.trigger does exactly that

**Comment by zhaoxuyll** [comment]
> you should read the docs search.trigger does exactly that

I notice this option in config, but confused how to use. Can you provide an example?

![image](https://github.com/folke/flash.nvim/assets/3224165/b27b6dd2-b221-49a5-9125-2267813ad2d3)

**Comment by max397574** [comment]
set it to a string like in a mapping e.g. "a" or "<c-r>"
and then you have to hit this character to be able to use the labels

**Comment by zhaoxuyll** [comment]
> set it to a string like in a mapping e.g. "a" or "" and then you have to hit this character to be able to use the labels if I understand the title of this issue correctly (even though you didn't explain it in the description) you perhaps want to set this to `"<cr>"`

I change `<Enter>` to `<Cr>`.


Sorry for not being clearly described. The video below is my configuration. I want to use `/` to enter a search without displaying labels, and when stop searching and display a label when you enter `<Cr>`.

https://github.com/folke/flash.nvim/assets/3224165/0b0273a5-d6f2-413b-960d-a899ff1b4707

**Comment by max397574** [comment]
You're describing exactly what this setting should do.
I think the labels will still show but you can type the characters savely without jumping to them.

**Comment by IndianBoy42** [comment]
> when typing "use", the r tag appears, and when you type r again, you perform a jump instead of continuing to enter the search condition "username".

This should never happen right? the labels are chosen to never conflict with possible continuations

Pretty much only if you have `max_length` set, which you should know and adjust your workflow for

**Comment by folke** [comment]
This should only happen when the word you are searching for is not in the buffer.

You can also use those options the others mentioned
