### ISSUE TITLE
feature: clever-f like repeat motion with the same

### ISSUE THREAD

**Issue by pBorak** [folke/flash.nvim#26]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

Both [flit.nvim](https://github.com/ggandor/flit.nvim)  and [clever-f.vim](https://github.com/rhysd/clever-f.vim) allow repeating the f/F/tT motion with the same key instead of ; and , usage.

### Describe the solution you'd like

Allow remapping keys that go to the next match or repeat the motion character.

_No response_

**Comment by folke** [comment]
That's already how flash works

**Comment by pBorak** [comment]
@folke Sorry for the confusion, for me it correctly goes forwards with consecutive f/t but when hit F or T it does not go back to previous occurrences.

**Comment by folke** [comment]
That actually makes a lot of sense. I've just change the implementation to behave like that.
