### ISSUE TITLE
feature: Handle searches with no match

### ISSUE THREAD

**Issue by chrisgrieser** [folke/flash.nvim#29]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

The FR is concerned with using flash via the search `/`.

Commonly, search is used for two scenarios:
1. You search for all occurrences of a string, e.g. you search for "foo" in the entire buffer. In this case you type `/foo`, followed by one of flash's hints or by `<CR>nn…`
2. You already know the exact location you want to go to and use `/` as quickest method of getting there. You search for a unique term and instinctively type `/foobarbaz<CR>` knowing you will get to your desired location.

Now the issue is, for scenario 2 I *sometimes* misremember what the unique string was, e.g. it was actually "foobangbaz", not "foobarbaz". Normally, this is not a big deal, since I get the "no search match found" message, and repeat the search with a shorter search term:  `/<up><BS><BS>…`.

However, with flash's modification of the search, misremembering a string can cause some trouble: After typing `fooba`, no further matches are found, so the next character `r` is interpreted as a hint character, and jumps you to a location in your buffer with `fooba` and leaves the command line. The remaining keystrokes `baz<CR>` are then interpreted as normal mode commands, resulting in `jump word backwards, append 'z' and a line break`. 

By the time I notice that "foobarbaz" actually does not occur in my buffer, I have effectively already jumped to random location and made some unintended changes. In the regular search, when typing `/foobarbaz<CR>` with no match in the buffer, I'd just get a "no match found" message without jumping to a different location or modifying the buffer.

All in all, the combination of using search for jumping to specific locations, typing quickly,  and misremembering the string results in somewhat undesired results when using flash. To prevent that, I kinda have to force myself to slow down when searching, to prevent that I unintentionally type a hint character.

### Describe the solution you'd like

One solution could be to introduce a new option for having to press the hint character twice before jumping, i.e. requiring `rr` to jump instead of a single `r`. This would make unintended jumps much less likely, wouldn't slow down flash too much, and still require only one letter `r` as hint character.

But yeah, I could not really think of a good solution for this problem that does not introduce any drawbacks, maybe you or someone else has a better idea? 😕 

### Describe alternatives you've considered

The only alternatives I can think of is disabling flash for `/` search or forcing myself to type much more slowly when searching for a string.

The first would be a bummer, since I quickly grew to love flash for `/`, the latter would be kinda annoying and defeating the purpose of jumping around more quickly.

**Comment by max397574** [comment]
I think `trigger` is what you're looking for

**Comment by chrisgrieser** [comment]
Hmm, I haven't though of that one, yeah. It's a bit inconvenient though, the double-keypress I suggested would at least reduce the issue a bit.

However, I also tried setting this, but I think it might not be working for the `/` search anyway? 🤔  Tried both, `.search.trigger` and `modes.search.search.trigger`

**Comment by folke** [comment]
@chrisgrieser I only added that feature half an hour ago. Did you update the plugin?

**Comment by chrisgrieser** [comment]
Oh, I actually haven't. Oh boy, by the time I have written this lengthy issue, there have been a dozen new commits already, you are just too quick :D

Yeah, after updating, it works. It's an okay-ish solution, but the extra key press does feel a bit cumbersome. I think my double-keypress suggestion could be a smoother solution, though I am not sure without having tried it out.

Guess the accidental jump problem is tricky to prevent and might not have a perfect solution 😕

**Comment by theol0403** [comment]
@chrisgrieser what do you think of trigger being CR? In that case it might work more like regular search, where you press CR and but then use a jump label to select the actual search item.

**Comment by chrisgrieser** [comment]
@theol0403 it does not accept `<CR>` as trigger. And I think even if it would, it would not be desirable, since it would result in having to press `<CR>` two times and stuff? 🤔
