### ISSUE TITLE
feature: Can jump label (highlight character) show at the beginning of matched pattern?

### ISSUE THREAD

**Issue by hrcHarry** [folke/flash.nvim#291]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

Hi

When we use `/` to search some word, the jump label is shown at the end of the currently matched pattern, like the following example.

![](https://upload.cc/i1/2023/12/07/CDLY31.png)

If we are not familiar to the set of similar variable names (i.e., we do not know the next character), the jump label shown at the end will hide the next character to reduce efficiency that narrowing down the "jumping" candidates. 

For example, there are a bunch of `label` and `labal` in code; to search `labal`, we type `/lab` and get some candidates. Remember that we are not familiar to these variable names. Now the jump label hide the next character of `/lab` to obstruct the searching --- we are not sure that what is the next character --- like the figure shown above.

### Describe the solution you'd like

Let the jump label show at the beginning of the matched pattern, as shown below.
![](https://upload.cc/i1/2023/12/07/4Fg0sM.png)

### Describe alternatives you've considered

None.

### Additional context

The jump label which is shown at the beginning is fine because, in this example, to search `labal`, we must know the first character is `l` and, then, we type `/l` without obstacle.

**Comment by shivamchandra75** [comment]
@hrcHarry 
I think what you are looking for is `label.before` set it to true and set `label.after` to false.

<img width="1427" alt="Screenshot 2024-01-09 at 9 43 33 PM" src="https://github.com/folke/flash.nvim/assets/83809266/46b9cc22-200e-44fb-85c2-92ec14ec6879">

# but I still think it would be great if we had an option to display jump lablel on top of the search character

**Comment by xzbdmw** [comment]
> @hrcHarry I think what you are looking for is `label.before` set it to true and set `label.after` to false.
> 
> <img alt="Screenshot 2024-01-09 at 9 43 33 PM" width="1427" src="https://private-user-images.githubusercontent.com/83809266/295266827-46b9cc22-200e-44fb-85c2-92ec14ec6879.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzMTgzMzgsIm5iZiI6MTcwNjMxODAzOCwicGF0aCI6Ii84MzgwOTI2Ni8yOTUyNjY4MjctNDZiOWNjMjItMjAwZS00NGZiLTg1YzItOTJlYzE0ZWM2ODc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDAxMTM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0ZDFiZGNjMmEyNjFkNjFkNGI3NzZmYzZmOGI5ZDFlOGZiMzBkMWViZmEyMzczMDllNTMzYTFkOTJjZTBlNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qpNr_jNCk9D1bXUp_V4oMUkmA4zslmQ70bfJZ8AS_ww">
> # but I still think it would be great if we had an option to display jump lablel on top of the search character

Could you share your noice config that makes search pop up like your screen? I tried and failed.

**Comment by hrcHarry** [comment]
> > @hrcHarry I think what you are looking for is `label.before` set it to true and set `label.after` to false.
> > <img alt="Screenshot 2024-01-09 at 9 43 33 PM" width="1427" src="https://private-user-images.githubusercontent.com/83809266/295266827-46b9cc22-200e-44fb-85c2-92ec14ec6879.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzMTgzMzgsIm5iZiI6MTcwNjMxODAzOCwicGF0aCI6Ii84MzgwOTI2Ni8yOTUyNjY4MjctNDZiOWNjMjItMjAwZS00NGZiLTg1YzItOTJlYzE0ZWM2ODc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDAxMTM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0ZDFiZGNjMmEyNjFkNjFkNGI3NzZmYzZmOGI5ZDFlOGZiMzBkMWViZmEyMzczMDllNTMzYTFkOTJjZTBlNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qpNr_jNCk9D1bXUp_V4oMUkmA4zslmQ70bfJZ8AS_ww">
> > # but I still think it would be great if we had an option to display jump lablel on top of the search character
> 
> Could you share your noice config that makes search pop up like your screen? I tried and failed.

Hi. In packer, I tried the similar setting and it fails.
You may use flash.nvim installed by Lazy.nvim and configured as shivamchandra75's setting. It works. Hope that helps.
