### ISSUE TITLE
bug: can not work with <C-o>

### ISSUE THREAD

**Issue by soluty** [folke/flash.nvim#293]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

windows 10

### Describe the bug

<C-o> command in insert mode, can call a lua function and then back to insert mode. like this
`map({ "i" }, "<A-s>", '<C-o>:lua print("flash")<cr>', { desc = "" })`
but if i call jump function from flash, it can work well only i used the first time.
`map({ "i" }, "<A-s>", '<C-o>:lua require("flash").jump()<cr>', { desc = "" })`
as it works fine in first time, so that may be there is a bug not in nvim but in flash plugin

### Steps To Reproduce

`map({ "i" }, "<A-s>", '<C-o>:lua require("flash").jump()<cr>', { desc = "" })`
then press alt+s , 

### Expected Behavior

can done search and then back into insert mode

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "folke/flash.nvim", opts = {} },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
vim.keymap.set({ "i" }, "<A-s>", '<C-o>:lua require("flash").jump()<cr>', { desc = "" })
```

**Comment by bluss** [comment]
It works for me with this tweak:

`map({ "i" }, "<A-s>", '<C-o><Cmd>lua require("flash").jump()<cr>', { desc = "" })`

Using `<cmd>` is the recommended way in general.
