### ISSUE TITLE
feature: suppress E486 error during regular search

### ISSUE THREAD

**Issue by narutohahahaha** [folke/flash.nvim#296]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

Currently there is such a confusing behavior when doing a regular search:

1. type in a few characters (n characters) to get the candidate
2. type in a specific hint character to jump
3. a E486 error message shows up saying the pattern---n characters + 1 hint character---is not found
4. hint "enter". The jump is confirmed and actually happens

I believe what happens in step-3 is confusing to users. It took me a while to realize that this is the error message for the regular search itself.

### Describe the solution you'd like

I suggest suppress E486 errors when flash is integrated into regular search.

### Describe alternatives you've considered

another solution might be intercepting every character the user types in and do a few checks, so a character is only bypassed to the regular search if it does not match any hint characters.

**Comment by JohnDoeDoe** [comment]
I get this error message also.
