### ISSUE TITLE
bug: `<esc>` key not working due to remap

### ISSUE THREAD

**Issue by JeanMertz** [folke/flash.nvim#302]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-80f75d0

### Operating system/version

macOS 14.1

### Describe the bug

Using `<Esc>` to disable Flash doesn't work for me, probably because I remapped my key as such:

```
<Cmd>lua MiniMap.refresh({}, {lines = false, scrollbar = false})<Cr><Cmd>nohlsearch<Cr>
```

### Steps To Reproduce

n/a

### Expected Behavior

`<Esc>` should move out of "Flash mode".

**Comment by JeanMertz** [comment]
To clarify; `<Esc>` works as expected in search mode (e.g. `/` or `?`), but _not_ in char mode (`f`, `F`, etc.).

**Comment by JeanMertz** [comment]
I resolved it by adding the following to my custom keymap:

```vim
<Cmd>lua require('flash.plugins.char').state:hide()<Cr>
```

Not sure if this is the right approach (it appears so, looking at the code), but it works. Posting it here for anyone else running into this.

**Comment by phanen** [comment]
Same problem, but I found the root cause is that my `<esc>` is mapped previously.
 
Work it out by append this to my previous `noremap`:
```lua
vim.api.nvim_feedkeys(vim.keycode "<esc>", "n", false)
```

**Comment by cameronr** [comment]
For anyone finding this in google, LavyVim has a clever solution where it includes the escape key in the mapping, which gives flash (and any other plugin that might care) a chance to see the escape key

```lua
-- Clear search with <esc>
map({ "i", "n" }, "<esc>", "<cmd>noh<cr><esc>", { desc = "Escape and Clear hlsearch" })
```
