### ISSUE TITLE
feature: Clear search highlights with CTRL-L

### ISSUE THREAD

**Issue by zoriya** [folke/flash.nvim#306]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

The default CTRL-L command on vim is used to redraw the screen and clear highlights.

### Describe the solution you'd like

Flash's highlights should also get cleared when this key is pressed.
(I guess from [here](https://github.com/folke/flash.nvim/blob/48817af25f51c0590653bbc290866e4890fe1cbe/lua/flash/plugins/char.lua#L152), but I did not try to fix it, I could write a PR if you want)

### Describe alternatives you've considered

Manually map CTRL-L to clear flash, but there is no API to clear flash highlights.

**Comment by GustafB** [comment]
+1 for having a way to clear the search highlights

**Comment by folke** [comment]
highlights are cleared with `<esc>`, not `<ctrl-l>`

**Comment by GustafB** [comment]
Afaict (very possible I've misconfigured something) the highlights from `search` are indeed cleared, but not from `{f, F, t, T}`.

Thanks for the prompt response @folke, love your work!

Here's a quick screenshare

![WindowsTerminal_A94q84mGIT](https://github.com/folke/flash.nvim/assets/28737105/93818223-e7ec-4ebf-8c73-e47ed3badfd9)

**Comment by HynDuf** [comment]
I got this too, highlights from `{f,F,t,T,;,.}` isn't cleared with `<Esc>` (which is kinda annoying).
