### ISSUE TITLE
feature: Predefined pattern selection

### ISSUE THREAD

**Issue by morfert** [folke/flash.nvim#32]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

I would like to match and jump to treesitter query matches or regex patterns and select the entire match. [Flash](https://github.com/folke/flash.nvim) has the `jump.pos = 'range'` option which makes immediate selection trivial. The problem is that if I use a pattern in my `flash.jump( { search = { mode = 'search' }, pattern = [[ \v\w+ ]], jump = { pos = 'range' } } )` it correctly highlights all the matches but only adds labels to a few matches near the cursor and expects more input to filter the remaining results. Now I can type the characters that follow the desired match to filter and receive a label but upon jump the additional characters are also included in the range selection.
#### Initial State
![image](https://github.com/folke/flash.nvim/assets/100343258/fd13a7a4-3f63-458e-9c84-5b860f53357f)
#### Start Jump
![image](https://github.com/folke/flash.nvim/assets/100343258/11ce5913-d027-446b-a0f3-30ff3091f56a)
#### Target string `folke` and input `/`
![image](https://github.com/folke/flash.nvim/assets/100343258/89b8fcaf-2510-4273-a605-94a6921975f6)
#### Input `a` to select
![image](https://github.com/folke/flash.nvim/assets/100343258/ce4b8f9d-c939-4282-b0ba-58bf885bf64f)
I wanted to select just `folke` but selected `folke/` since the `/` became part of the pattern.

### Describe the solution you'd like

I would like for all possible matches to be given a label without additional input/filtering. Additionally I would also like to be able to match treesitter queries so that I can search for more complicated patterns.

### Describe alternatives you've considered

I've tried using a function as search mode which ignores the string and just returns the initial pattern but it results in the same few matches being labelled.

### Additional context

This may be beyond the scope of [flash](https://github.com/folke/flash.nvim) since it tries to have single character labels.
In a scenario where there are more matches than labels those would be inaccessible. This could be solved by having a special character like `<space>` in [leap.nvim](https://github.com/ggandor/leap.nvim) to select the next range of matches.

**Comment by folke** [comment]
Try this instead:

```lua
require("flash").jump({
  search = {
    mode = function(pattern)
      return ([[\v<%s\w+>]]):format(pattern)
    end,
  },
  jump = { pos = "range" },
})
```

After typing `s`, you'll get this:

![image](https://github.com/folke/flash.nvim/assets/292349/9bd7a41e-02d6-4c53-a304-e0f9e1b23ace)

**Comment by morfert** [comment]
It works to match words that start with a specific character but what if I wanted to match all words currently visible?

**Comment by folke** [comment]
It's a bit of a hack, but you can start with `pattern = "."`

```lua
require("flash").jump({
  pattern = ".",
  search = {
    mode = function(pattern)
      return ([[\v<%s\w+>]]):format(pattern)
    end,
  },
  jump = { pos = "range" },
})
```

**Comment by folke** [comment]
But doing it this way would prevent typing more characters... Need to think about this

**Comment by morfert** [comment]
Yes, it would probably have to be a different mode like treesitter.

**Comment by folke** [comment]
```lua
require("flash").jump({
  pattern = ".",
  search = {
    mode = function(pattern)
      if pattern:sub(1, 1) == "." and #pattern > 1 then
        pattern = pattern:sub(2)
      end
      dd(pattern)
      return ([[\v<%s\w+>]]):format(pattern), ([[\v<%s]]):format(pattern)
    end,
  },
  jump = { pos = "range" },
})
```

**Comment by morfert** [comment]
Yeah, for words this is fine.
I'd also like to do this for treesitter queries but maybe that should be a separate issue for adding more pattern options?

**Comment by folke** [comment]
What exactly would you want to do for treesitter queries? Can you give an example?

**Comment by folke** [comment]
Jump to a position, make a Treesitter selection and jump back:

This should be bound to a keymap like `<leader>t`.
Then you could do `y<leader>t` to remotely yank a Treesitter selection.

```lua
require("flash").jump({
  action = function(match, state)
    vim.api.nvim_win_call(match.win, function()
      vim.api.nvim_win_set_cursor(match.win, match.pos)
      require("flash").treesitter()
      vim.api.nvim_win_set_cursor(match.win, state.pos)
    end)
  end,
})
```

**Comment by morfert** [comment]
I had a custom textobject defined in `{nvim_config}/queries/elixir/textobjects.scm` for arguments. It would match arguments in function definitions and function calls. I would like to do `<leader>fa` and see all arguments from definitions and calls be highlighted and have labels. Then select the desired argument, the cursor will move there and visually select it. Then I can use normal vim editing commands.
[Nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter/tree/master) provides helper functions, specifically `query.get_matches` which takes the query name and buffer number and returns the matches.

**Comment by morfert** [comment]
These pattern matches would end up being file type specific though.

**Comment by folke** [comment]
You'll have to write a custom matcher for that. You can check some of the examples in the docs or the code of the treesitter plugin.
