### ISSUE TITLE
feature: there's no easy way to jump to the last character of the line?

### ISSUE THREAD

**Issue by name-snrl** [folke/flash.nvim#320]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

I can't jump to the last character of the line. May I missed something in doc, but I read it twice.

### Describe the solution you'd like

I used leap.nvim and just type <Space> at EOL.

### Describe alternatives you've considered

To go back to leap.nvim, idk. :D
But flash is awesome!

### Additional context

```lua
{
    'folke/flash.nvim',
    ---@type Flash.Config
    opts = {
      label = { uppercase = false },
      prompt = { enabled = false },
      modes = {
        search = { enabled = false },
        treesitter = { label = { rainbow = { enabled = true, shade = 2 } } },
        treesitter_search = { label = { rainbow = { enabled = true, shade = 2 } } },
      },
    },
    -- stylua: ignore
    keys = {
      'f', 'F', 't', 'T',
      { 'gs', function() require('flash').jump() end, mode = { 'n', 'x', 'o' } },
      { 'gz', function() require('flash').treesitter() end, mode = { 'n', 'x', 'o' } },
      { 'gZ', function() require('flash').treesitter_search() end, mode = { 'o', 'x' } },
      { 'r', function() require('flash').remote() end, mode = 'o' },
      {
        'ygw',
        function()
          require('flash').jump {
            action = function(match, state)
              vim.api.nvim_set_current_win(match.win)
              vim.api.nvim_win_set_cursor(match.win, match.pos)
              vim.cmd.norm { args = { 'yiw' }, bang = true }
              state:restore()
            end,
          }
        end,
      },
    },
  }
```

**Comment by gennaro-tedesco** [comment]
Is this different than the general vim motion `g_`?

**Comment by name-snrl** [comment]
> Is this different than the general vim motion `g_`?

Of course, because the jump works across all windows and rows

**Comment by gennaro-tedesco** [comment]
> I can't jump to the last character of the line.

but then you do not want to jump to the last character of the line, you want to mark/jump the last character-s of _each_ line.

**Comment by name-snrl** [comment]
> but then you do not want to jump to the last character of the line, you want to mark/jump the last character-s of _each_ line, is it correct?

What? I just want to jump to any character on the screen, including the last characters of the lines.

**Comment by brunobmello25** [comment]
Additionally, it would be nice if we could also jump to blank lines.

With leap, you can just do this by pressing `s<space><space>` (assuming your "leap bind" is `s`). Then it would show labels for every blank line (even if it doesn't actually have two spaces) and you can jump directly to them

with flash this is not currently possible, I believe

**Comment by iamhrigved** [comment]
```lua
function()
    require("flash").jump({
	search = { mode = "search", max_length = 0 },
	label = { after = { 0, 0 } },
	pattern = "^",
    })
end
```
This function is provided in the "Examples" section which can be used to go to the beginning of a line, but not at the end.

I think we should find a regex to put in the `pattern` section which matches ^ AND $ that is, the beginning AND end of line.

**Comment by okuuva** [comment]
Hey, I managed to come up with a config that enables this. In order not to spam an old closed ticket too much, I put the example in a [show&tell discussion](#432). Let's continue the discussion there if needed.
