### ISSUE TITLE
feature: Treesitter: expand selection

### ISSUE THREAD

**Issue by ralph-bergmann** [folke/flash.nvim#335]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

First, I like the plugin, but I can't use it as often as I wish.

My day-to-day job is developing Flutter apps (written in Dart). There, I have a lot of `<Constructor>()`. But the Treesitter mode (`S`) only selects the body of the constructor without the class name:

<img width="1015" alt="SCR-20240504-czmq" src="https://github.com/folke/flash.nvim/assets/1191649/e55b0818-0890-4e88-b9df-46a5237d882f">

Is there a way to expand the selection to include the class name? See `AnimatedBuilder` or `MaterialApp`.

### Describe the solution you'd like

In an ideal world, the plugin would automatically add the name of the constructor to the selection. But it would be enough to have a function to do this manually.

### Describe alternatives you've considered

I've tried `;` but it doesn't do what I'm looking for.

**Comment by ralph-bergmann** [comment]
I think I have found a way to achieve what I wanted.
1. select code block with `S`
2. jump to the start/end of the selection with `O`
3. increase/decrease selection

**Comment by folke** [comment]
That's caused by the treesitter parse tree, so not possible to fix...
