### ISSUE TITLE
jump labels in search mode not working anymore by default

### ISSUE THREAD

**Issue by vdegenne** [folke/flash.nvim#340]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

Fedora 39

### Describe the bug

When typing `/` in a document and seraching something, the jump labels are not displayed anymore. It was working before and I didn't change my config file prior to this issue.

I fixed it by adding `enabled = true` in `modes.search` in my flash config file.

Odd. Also the changelog doesn't specify anything about this new behavior so I wanted to report in case it's an inconsistency.

### Steps To Reproduce

(steps in description of the bug)

### Expected Behavior

jump labels in search mode

**Comment by folke** [comment]
Yes, there was a breaking change about this.
https://github.com/folke/flash.nvim/commit/2411de6fd773ab5b902cf04f2dccfe3baadff229

**Comment by vdegenne** [comment]
Ah sorry it was obvious.
I like this default more by the way.
