### ISSUE TITLE
feature: Line Jump 

### ISSUE THREAD

**Issue by tahseenjamal** [folke/flash.nvim#352]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

Currently if I have to jump to a line I have to type the line relative number above / below the current position and then press j or k

This needs moving to the numeric pad to press the line number, which can be a single to even a two digit number on numeric pad. 

Because of type, we are mostly more conversant with alphabets' position compared to that of numbers on the keyboard

### Describe the solution you'd like

Line Function in Flash, using which all numbers should switch to a-z and A-Z on the above and below my line

And that I have to just press one character to reach that line, this would cover 26 lines above and 26 lines below. Above it we can have a combination character like / or ; 

So beyond 26 characters above another 26 characters of a-z would be available but as ;a to ;z

And line wise for below ;A to ;Z

### Describe alternatives you've considered

One option of line jump is with hop.nvim but this plugin is not supported any more by the author

**Comment by folke** [comment]
There's an example to jump to a line in the docs. smh
