### ISSUE TITLE
bug: broken macros when using 'f' character jump

### ISSUE THREAD

**Issue by skrobul** [folke/flash.nvim#366]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.11.0-nightly+4e8efe0

### Operating system/version

Linux Nixos 24.05

### Describe the bug

I am getting weird behaviour while trying to record a simple macro, similar to https://github.com/folke/flash.nvim/issues/143, but not quite the same because I don't use dot repeats here.

### Steps To Reproduce

1. `nvim -u repro.lua`
2. Paste the input text which we can operate on:
Macro that doesn't work:

```
email_recipient = salt['pillar.get']('keepalived:email:recipient', 'example@example.com')
email_sender = salt['pillar.get']('keepalived:email:sender', 'other@example.com')
email_smtp = salt['pillar.get']('keepalived:email:smtp', 'smtp1.example.com')

Macro line:
f=hdf,i:f)x
```
3. Place the cursor below the macro, and yank the line into 'q register: `"qy$`
4. Try to execute macro `@q` on any of the lines  

### Expected Behavior

Executing the macro with `flash.nvim` on a `email_smtp` line results in following output:

```
email_smtp: salt['pillar.get']('keepalived:email:smtp', 'smtp1.example.com'
```

In vanilla neovim, running the same macro produces correct line:

```
email_smtp: 'smtp1.example.com'
```

Interestingly, if you record another macro using Ctrl+C to exit insert mode instead of Escape, the macro works.
It seems to populate the macro register with some odd characters though:

 `㵦ﶀ栵晤耬㗽㩩̃⥦ﶀ砵` github interprets those as some Chinese unicode, but this is how they look in vim:
![image](https://github.com/user-attachments/assets/6986f2d9-e164-4ec2-bf1c-6e562e2d50af)

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/flash.nvim", opts = {} },
  },
})
```

**Comment by chuan29812** [comment]
sad, im still experiencing this. i tried for hrs when i thought it was the mark plugin i was using or i was doing the macro wrong. it turned out to be this. i guess the only workaround is turning it off before recording?

**Comment by chuan2984** [comment]
> I'm also having problems with this. @chuan29812 do you know a way to disable the plugin while recording a macro? For the time being I'll disable char jumps as it makes macro recording unusable.

@radgeRayden yup, same. i cannot for the life of me figure out a way for this to not mess up macros, you just have to disable it. i really like the highlighting but oh well

**Comment by celsobenedetti** [comment]
Still relevant

**Comment by Kaiser-Yang** [comment]
#487 should fix this, you can check it.
