### ISSUE TITLE
feature: Is it possible to have a Saner version of `;,`

### ISSUE THREAD

**Issue by mau-mauricelim** [folke/flash.nvim#367]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

I think it would be nice to have a Saner version of `;,` like the feature below. I.e. `;` should always search forward and `,` should always search backwards.
https://github.com/mhinz/vim-galore?tab=readme-ov-file#saner-behavior-of-n-and-n

### Describe the solution you'd like

It would be nice if there is a way to set a keymap that uses some of the underlying function so that I am able to achieve the desired behaviour described.

Probably something like:
```
vim.keymap.set('n', ';', function() require("flash").jump({
  search = { forward = true, wrap = false, multi_window = false },
}) end, { desc = 'Search forward only' })
```

### Describe alternatives you've considered

I've tried some of the above functions to try and achieve it but can't seem to do it. Any help to point me in the right direction would be appreciated!

**Comment by mau-mauricelim** [comment]
Is anybody able to help with this?

**Comment by folke** [comment]
Check the readme (config section) for char_actions
