### ISSUE TITLE
feature: run a custom function on jump

### ISSUE THREAD

**Issue by dizzib** [folke/flash.nvim#368]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

I would like to automatically drop a new [trailblazer](https://github.com/LeonHeidelbach/trailblazer.nvim) mark on a successful flash jump i.e. as soon as a flash label is selected.

### Describe the solution you'd like

1. emit an ‘on-jump’ event for autocmd to listen for, or
2. in flash options, specify a custom function to run on jump. In my case it would be:

```
function()
  require'trailblazer'.new_trail_mark()
end
```

### Describe alternatives you've considered

I was unable to find an appropriate autocmd, so I tried wrapping the on_jump function in [jump.lua](https://github.com/folke/flash.nvim/blob/34c7be146a91fec3555c33fe89c7d643f6ef5cf1/lua/flash/jump.lua#L226) but couldn’t get it to work.

**Comment by b0ae989c** [comment]
How about using `flash.config.action`? It is invoked for all jumps (when it's defined).

See https://github.com/folke/flash.nvim/blob/34c7be146a91fec3555c33fe89c7d643f6ef5cf1/lua/flash/state.lua#L154-L156

**Comment by dizzib** [comment]
Thank you for pointing me in the right direction. I was able to get this to work by specifying opts.action as follows:

```
  opts = {
    action = function(match, self)
      local Jump = require('flash.jump')
      Jump.jump(match, self)
      Jump.on_jump(self)
      require('trailblazer').new_trail_mark()
    end,
  }
```
