### ISSUE TITLE
bug: Weird behavior when using f in a macro

### ISSUE THREAD

**Issue by sufftea** [folke/flash.nvim#379]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.1

### Operating system/version

Ubuntu 24.04.1 LTS

### Describe the bug

My macros fail to execute to the end when I use `f` in them. I've checked the issues #143 and #366, but what I'm experiencing is different.

My guess is that `f` stays activated even after jumping to the character during macro execution. I do have `autohide = true`.

### Steps To Reproduce

1. Have this code:
```go
{
  Profile: entities.Profile{
    Username: "xX_alice_Xx",
    Name:     "alice",
  },
  Id: "user1id",
}
```

2. Record a macro that removes the outer struct and leaves only the Profile:
```
vf{hdf}nvf}d    (The exact macro I recorded)
vf{hdf}lvf}d    (The translated version, because I use different keys for motions)
```
The result:
```go
{
    Username: "xX_alice_Xx",
    Name:     "alice",
  },
```
3. Execute the macro on the same piece of code. The result:
```go
{                      
		Username: "xX_alice_Xx", 
		Name:     "alice",  
	},                   
	Id: "user1id",       
},                     
```
4. (Bonus) Record the same macro, but press `<esc>` every time before using `f`:
```
vf{hd^[f}n^[vf}d 
vf{hd^[f}l^[vf}d 
```
Now it works correctly, but it's inconvenient.

### Expected Behavior

The result of macro execution is the same as during its recording.

### Repro

```lua
{
    "folke/flash.nvim",
    event = "VeryLazy",
    ---@type Flash.Config
    opts = {
      -- ...
      modes = {
        char = {
          jump_labels = false,
          autohide = true,
          multi_line = true,
          label = {
            exclude = "chtn",
          },
          char_actions = function()
            return {
              [";"] = "next", -- set to `right` to always go right
              [","] = "prev", -- set to `left` to always go left
            }
          end,
        },
      },
    },
    -- stylua: ignore
    keys = {
      { "s", mode = { "n", "x", "o" }, function() require("flash").jump() end, desc = "Flash" },
      { "S", mode = { "n", "x", "o" }, function() require("flash").treesitter() end, desc = "Flash Treesitter" },
      { "r", mode = "o", function() require("flash").remote() end, desc = "Remote Flash" },
      { "R", mode = { "o", "x" }, function() require("flash").treesitter_search() end, desc = "Treesitter Search" },
      { "<c-s>", mode = { "c" }, function() require("flash").toggle() end, desc = "Toggle Flash Search" },
    },
  }
```

**Comment by porridgewithraisins** [comment]
I found a "workaround", press esc during the macro execution after `f<char>`. So
instead of `qtf(alq` (record a macro to `t` to go to next `(` and then insert an `l` after), you would do `qtf(<esc>alq`

BTW, this same breakage is there in `:norm` as well, so like
`:norm f(al` breaks as well, to insert an `<esc>` there you have to do CTRL+V then press escape, it will insert the escape character code or whatever there. That is, `:norm f(`[here type ctrl+V esc]`al` works just fine. The command line will look like `norm f(^[al` at the end with the `^[` grayed out.
