### ISSUE TITLE
bug: Some labels in VS Code are missing.

### ISSUE THREAD

**Issue by chaudry-786** [folke/flash.nvim#384]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.11.0-dev-1045+gb922b7d6d

### Operating system/version

Ubuntu 24.04.1 LTS

### Describe the bug

When calling treesitter or treesitter_search,  some labels are missing. please see the screenshot.
![Screenshot from 2024-10-26 13-41-45](https://github.com/user-attachments/assets/0456e537-1116-482b-b329-6fdf1ef1db01)

QQ (slightly related): Can I change the strategy of how labels are displayed when multiple node start on the same position. E.g In the screenshot above (in terminal, left) I want "cd" and "ab" at the start position to swap places.

### Steps To Reproduce

1. Launch nvim with "nvim -u ~/.config/nvim/repro.lua"
2. For VS Code, set this setting:     "vscode-neovim.neovimInitVimPaths.linux": "~/.config/nvim/repro.lua"
3 .  Create a sample lua file
```
local filename = "vscode-remote:/home/user/some_dir"
if string.match(filename, "^vscode%-remote") then
    filename = string.match(filename, "/home.*")
end
print(filename)
```

4. Take the cursor to "filename" on the first line and invoke "treesitter" with "S" mapping. 

### Expected Behavior

In VS Code some labels are missing but everything is fine when neovim is run in terminal.

### Repro

```lua
-- Plugin manager
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
        "git",
        "clone",
        "--filter=blob:none",
        "https://github.com/folke/lazy.nvim.git",
        "--branch=stable",
        lazypath,
    })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
    {
        "nvim-treesitter/nvim-treesitter",
        build = ":TSUpdate",
        dependencies = "nvim-treesitter/nvim-treesitter-textobjects",
    },
    {
        "folke/flash.nvim",
        event = "VeryLazy",
        ---@type Flash.Config
        opts = {},
        -- stylua: ignore
        keys = {
            { "S", mode = { "n", "x", "o" }, function()
                require("flash").treesitter({
                    label = {
                        rainbow = {
                            enabled = true,
                            shade = 4
                        }
                    },
                    highlight = {
                        backdrop = true,
                        matches = false
                    },
                    search = {
                        multi_window = false
                    }
                })
            end, desc = "Flash Treesitter" },
        },
    }
})
```

**Comment by gjf7** [comment]
@chaudry-786 Hi, thanks for reporting. Looks like this bug is on vscode-neovim side, could u open a issue at https://github.com/vscode-neovim/vscode-neovim/issues ?

**Comment by folke** [comment]
Closing as upstream. Thanks
