### ISSUE TITLE
bug: Impossible to remove FlashMatch styling

### ISSUE THREAD

**Issue by downhiller** [folke/flash.nvim#388]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

CentOS Stream 9

### Describe the bug

I'd like to remove the FlashMatch styling.  I feel having the labels (and FlashCurrent) is enough, and FlashMatch adds too much visual distraction.

If I run

    :hi FlashMatch guifg=none guibg=none

it works.  Gone is the highlighting.

However, it appears to be impossible to do this within `init.lua`.  I've tried vim.cmd, native lua, defered functions, `hi!` rather than `hi`, etc etc.

I can happily set it to any other color (`guifg=#ffffff guibg=#990000` etc), but as soon as I specify `none`, or `nil` nothing I can try in `init.lua` works.

If I specify red, it'll go red.

If I specify red, and then none, it'll go back to being linked to `Search`.

It seems be impossible to undo that link.  You can override it with a color, but not with a `none`/`nil`.

If I'm wrong I apologise, please show me what to do!

### Steps To Reproduce

1. Add `vim.cmd('highlight FlashMatch guifg=none guibg=none')` to `init.lua`
2. Relaunch `nvim`
3. Perform a flash search

### Expected Behavior

The matches shouldn't be highlighted (other than the "current" one)

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/flash.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
hl changes always needs to be done in a ColorScheme autocmd.
This is for every plugin in Neovim. Not a flash bug

**Comment by downhiller** [comment]
That was one of the many things I tried - it worked for colours, but not for "none"/"nil".

I'll try again, maybe I was being dumb(er than usual)

**Comment by folke** [comment]
Just link the group to `Normal` or set `nocombine = true`

**Comment by downhiller** [comment]
autocmd ColorScheme * highlight FlashMatch guifg=none guibg=none                                                                                                              autocmd ColorScheme * highlight FlashLabel guifg=#ffffff guibg=#cc0000

This gives me nice Labels with white on red, but Matches still same color as my `Search` highlight group.  Same if I replace `none` with `"none"`, `nil` or `"nil"`
