### ISSUE TITLE
feature: add a way to check if `flash` is currently active

### ISSUE THREAD

**Issue by simonmandlik** [folke/flash.nvim#389]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

I'm using `require("flash").prompt()` in statusline. One problem with that is that it is impossible to distinguish between `flash` jump not being active at all and `flash` jump being active but with empty pattern. In both of these cases `require("flash").prompt()` returns an empty string and thus it is not possible to tell from the statusline whether `flash` is active or not.

### Describe the solution you'd like

A function, named e.g. `flash.is_active` returning a boolean value. This would make it possible to display e.g. just the prefix and not the pattern in the statusline, showing the difference between the two aforementioned states.

**Comment by folke** [comment]
```lua
for state in pairs(require("flash.state")._states) do
  if state.visible then
    print("active")
  end
end
