### ISSUE TITLE
bug: better handling of folds

### ISSUE THREAD

**Issue by folke** [folke/flash.nvim#39]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

currently matches inside folds are labeled

### Describe the solution you'd like

need to think this through :)

### Describe alternatives you've considered

not really

**Comment by tssm** [comment]
Could this be an option? Jumping to folds is quite useful sometimes

**Comment by folke** [comment]
Whats the use-case? Using incremental mode?

**Comment by tssm** [comment]
No, just navigation. Sometimes I wanna jump to a fold and open it because the code I must read/modify is folded

**Comment by folke** [comment]
It doesn't seem to be possible to set extmarks on the folded line.

With something like nvim-ufo, you will see the markers

**Comment by folke** [comment]
@MariaSolOs I mean you can jump to the summary shown on the fold for a word in that fold.

Still need to make it so that a folded line also gets a label (one) when the text inside the fold matches the pattern.

**Comment by folke** [comment]
Added proper support for folds.

The fold line will now show the label of the first match inside a fold. See example below:

![image](https://github.com/folke/flash.nvim/assets/292349/2126970a-aca8-4fb8-91c8-f8fb846b4969)

**Comment by MariaSolOs** [comment]
> The fold line will now show the label of the first match inside a fold.

Why limit the label to the first match? Not asking you to change this BTW, I'm just curious :)

**Comment by folke** [comment]
Since you can't see the targets you are jumping to, I don't think it makes sense to show all the labels for items in the folds?

**Comment by MariaSolOs** [comment]
@folke What I had in mind is that say I'm jumping to the following line with `se`:

```
> fn folded_method () {
```

I thought something like this would happen (adding the labels to both occurrences of `e`):
```
> fn foldad_mxthod () {
```

**Comment by folke** [comment]
Oh you mean on the foldtext? That's not how it currently works. It's also not straightforward to map actual cursor positions to a position inside the foldtext.

The feature I did add is say you have a multiline fold and the pattern matches something in line 3 of your fold, then you'd still be able to jump to that

**Comment by MariaSolOs** [comment]
That makes sense, thanks for explaining!
