### ISSUE TITLE
feature: Better coloring as `eyelilner.nvim`

### ISSUE THREAD

**Issue by NormTurtle** [folke/flash.nvim#42]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

no, but kinda of for autism

### Describe the solution you'd like

use eyeliner IDEA of making things POP more , by adding RAINBOW 🌈  colors
having Plain colors isn't that good and its boring :( 

### Describe alternatives you've considered

no

### Additional context

thx for the plugin tho

**Comment by folke** [comment]
I don't use eyeliner myself, but this seems to be a very different plugin than flash. It highlights unique letters in for the ftFT motions.

I also don't really see anything mentioned regarding rainbow colors?

**Comment by NormTurtle** [comment]
@folke i understand the thing , 
but i just said, getting rainbow color🌈  would be making stuff eASY to fucos on some expectes
