### ISSUE TITLE
feature: more jump pos options

### ISSUE THREAD

**Issue by ouuan** [folke/flash.nvim#46]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

I want to use `jump` to simulate bidirectional `f`-and-`t`-like behaviors with labels.

### Describe the solution you'd like

For `t`-like behavior, I need a jump pos that is one character before the `start` pos.

~~For backward jumps, I need reversed `start` and `end`.~~

So here are the jump pos options needed:

- ~~`far`: `end` for forward jumps, `start` for backward jumps.~~
- ~~`near`: `start` for forward jumps, `end` for backward jumps.~~
- ~~`until` (maybe there's a better name?): `start`-1 for forward jumps, `end`+1 for backward jumps.~~
- `till-start` (maybe there's a better name?): `start`-1 for forward jumps, `start`+1 for backward jumps.

### Describe alternatives you've considered

I can continue using [my fork of `hop.nvim`](https://github.com/ouuan/hop.nvim/tree/fix-inclusive).

**Comment by ouuan** [comment]
I reconsidered it, and maybe I don't need the `far` and `near` options. It makes sense to always use `start` for `f`-like behavior. And I'd like `start`-1 and `start`+1 according to forward/backward for `t`-like behavior.

**Comment by folke** [comment]
If you want labels for ftFT motions, use this:

```lua
-- to use this, make sure to set `opts.modes.char.enabled = false`
local Config = require("flash.config")
local Char = require("flash.plugins.char")
for _, motion in ipairs({ "f", "t", "F", "T" }) do
  vim.keymap.set({ "n", "x", "o" }, motion, function()
    require("flash").jump(Config.get({
      mode = "char",
      search = {
        mode = Char.mode(motion),
        max_length = 1,
      },
    }, Char.motions[motion]))
  end)
end
```

Make sure to update flash first

**Comment by ouuan** [comment]
What about bidirectional ftFT 🤔

**Comment by folke** [comment]
add `wrap = true` right before `max_length` and remove `T`, `F` from the ipairs
