### ISSUE TITLE
feature: multi-character labels

### ISSUE THREAD

**Issue by ouuan** [folke/flash.nvim#47]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

When using `max_length = 1` and there are many matches, it seems impossible to jump to the farthest ones.

### Describe the solution you'd like

Use multi-character labels when single-character labels are not enough.

### Describe alternatives you've considered

Don't use `max_length = 1` and type more characters for far matches.

**Comment by ouuan** [comment]
I just come up with another alternative: highlight the next character when more characters are needed before a label is assigned. In this way, the next character visually looks like part of a "multi-character label".

**Comment by ouuan** [comment]
Another consideration is that a character could be at the end (i.e. at the end of a line or before a non-ASCII character) with no "next character" to type. So it's preferable to support multi-character labels.

**Comment by folke** [comment]
Thank you for the suggestion, but I'm not interested in adding this.
Flash is a search based navigation plugin. You typically just enter more characters to narrow down where you want to go.

setting max_length can be useful, but you're right that this way you won't be able to jump to all targets if there are more than all available labels.
