### ISSUE TITLE
feature: autoselect

### ISSUE THREAD

**Issue by max397574** [folke/flash.nvim#5]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

When I use the search with `s` and I type 2-3 characters often I already have a unique result. it's annoying that I still have to press `<cr>` to actually jump to that result.

### Describe the solution you'd like

autojump if there is only one result left

### Describe alternatives you've considered

press `<cr>` :(

**Comment by max397574** [comment]
thank you

**Comment by folke** [comment]
Just added this. Enable it with `config.jump.autojump = true`.

Do be aware that with `wrap=true` and/or `multi_window=true`, it would still only autojump if there's no other matches anywhere.
