### ISSUE TITLE
feature: Custom modes inheriting from other custom modes

### ISSUE THREAD

**Issue by IndianBoy42** [folke/flash.nvim#50]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

I like to define my custom action jumps using custom modes, so everything is in the config table, and the keymaps are just `.jump({mode = "diagnostics"})`, or something like that. There is a lot of repetitiveness here, the `search` and `jump` configs are the same across a lot of these (mainly 2 kinds of jumping, either fuzzy, or exact with `max_length = 2`). 

### Describe the solution you'd like

It would be nice if `config.modes.diagnostics.mode = "fuzzy"` would mean that `diagnostics` mode inherits from `fuzzy` mode.

### Describe alternatives you've considered

Just copy-pasting, or using local variables and `vim.tbl_deep_extend` myself. The latter approach breaks the nice almost declarative looking configuration with lazy.nvims opts key

**Comment by folke** [comment]
Added!

**Comment by IndianBoy42** [comment]
You are an absolute machine, thanks!

**Comment by IndianBoy42** [comment]
Oh, I think the order is actually not correct here.

If we have `mode = 'a'` in the keymapping, and `modes.a.mode = 'b'` and `modes.b.mode = 'c'`. We want the order of priority to be: `keymapping -> modes.a -> modes.b -> modes.c`, which means the order in the `tbl_deep_extend` has to be the opposite of that. but actually it becomes `modes.a, modes.b, modes.c, keymappings`. When recursively following `.mode` the closest  mode table is added to `all` first.

**Comment by folke** [comment]
Fixed properly now. Thanks!
