### ISSUE TITLE
feature: inclue text objects in ("flash").treesitter()

### ISSUE THREAD

**Issue by fecet** [folke/flash.nvim#52]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

Not a problem

### Describe the solution you'd like

Support selecting text object in("flash").treesitter()

### Describe alternatives you've considered

Now the  `("flash").treesitter()` only select TS nodes and works like https://github.com/mfussenegger/nvim-treehopper.
Can we let the candidates also include user defined text objects like https://github.com/gcmt/wildfire.vim?

For example, user can set a list of text objects, say `["i'", 'i"', "i)", "i]", "i}", "ip", "it"]`, then flash include them when activate  `("flash").treesitter()` (skip overlap)

**Comment by folke** [comment]
Thank you for the suggestion, but I think that Treesitter already covers 99% of the use cases
