### ISSUE TITLE
bug: when I scroll to the bottom with G, using flash scrolls to the first search result in the file.

### ISSUE THREAD

**Issue by D00mch** [folke/flash.nvim#53]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

MacOS 13.2

### Describe the bug

When I use "/" to search for a pattern, lets say "nvim", everything works as expected unless I see the last line of the file.

### Steps To Reproduce
```
G
/<pattern that appears on the lines that are above the screen\>
```

### Expected Behavior

I see search pattens on the screen without it scrolling to the top of the file.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "folke/flash.nvim", opts = {} },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
That's just incsearch? Disable flash and the result would be the same. 

Or do you mean something different?

**Comment by D00mch** [comment]
Indeed, the result remains the same even without flash. Apologies, I don't use Vim's search function often, as I'm more accustomed to using [Svart](https://gitlab.com/madyanov/svart.nvim) to jump to patterns. However, do you know how to eliminate this behavior?

**Comment by folke** [comment]
Then just use the jump mapping? There incremental search is disabled by default
