### ISSUE TITLE
feature: resume/cycle previous search (fF/tT or jump) with `;` `,`

### ISSUE THREAD

**Issue by andrevmatos** [folke/flash.nvim#54]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

Sometimes, it may be hard to go back to previous search state, and cycle through matches or labels. dot-repeat may help, but only until some text-changing operation is performed.

### Describe the solution you'd like

`;`/`,` remember the last used motion (`fF/tT` or `jump`), and will recover that mode and its state once invoked, with same labels. Pressing again will jump through matches forth or back, respectively.

### Describe alternatives you've considered

`jump` previous state could also be recovered with `<CR>` without any entry (e.g. `s<CR>`), like leap.
Currently `<CR>` without a pattern cancel jump mode, same as `<esc>`.

### Additional context

Recovering previous jump state is tricky. Dot-repeat only works if you haven't made a text-changing operation after last jump.

**Comment by folke** [comment]
You can easily implement this yourself. See the code you need below

```lua

local state = require("flash").jump({...})

-- If you want to reuse the last state, you can do
state:show()
```

**Comment by andrevmatos** [comment]
Didn't work, because just showing the `state` didn't allow me to input new keys (not even labels).
I managed to work-around here for now, by copying the `jump` commands, and adjusting it to recover and continue from previous state when it received just `<CR>`:
```lua
function flashJump(opts)
  local prevState = Repeat._states["jump"]
  local state = Repeat.get_state("jump", opts)
                                                                                               
  local first = true
  while true do
    local continue = false
    local c = Util.get_char()
    if c == nil then
      Repeat._states["jump"] = prevState
      break
    elseif c == Util.CR then
      if first and prevState then
        Repeat._states["jump"] = prevState
        state = prevState
        state:show()
        continue = true
      else
        -- jump to first
        state:jump()
        break
      end
    end
                                                                                               
    first = false
    if not continue then
      local orig = state.pattern()
                                                                                               
      -- break if we jumped
      if state:update({ pattern = state.pattern:extend(c) }) then
        break
      end
                                                                                               
      if state.opts.search.max_length and #state.pattern() > state.opts.search.max_length then
        state:update({ pattern = orig })
        state:jump()
        vim.api.nvim_input(c)
        break
      end
                                                                                               
      -- exit if no results
      if #state.results == 0 and not state.pattern:empty() then
        break
      end
      if #state.results == 1 and state.opts.jump.autojump then
        state:jump()
        break
      end
    end
  end
  state:hide()
  return state
end
```
Not very nice, and will probably break and require maintenance with every change, but at least I can easily recover previous jump with `s<CR>`.
Thanks

**Comment by folke** [comment]
You can now do the below instead:

```lua
require("flash").jump({continue = true})
```

**Comment by andrevmatos** [comment]
Can we get a boolean flag to tell when a `state` was cancelled (with `<esc>`), please?
This would make it possible to differentiate empty `<cr>` and `<esc>` and implement the alternative proposal (i.e. continuing on `<cr>` with empty pattern).
Thank you.

**Comment by andrevmatos** [comment]
How about continuing when user accepts an empty pattern? This way, one could simply type `s<cr>` to resume from a previous wrong/failed jump, and wouldn't require the user to remember yet another keymap.

My hack'ish implementation:
```lua
local Util = require('flash.util')
local Repeat = require('flash.repeat')
local prevState

function flashJump(continue)
  local aborted
  local opts = {
    continue = continue,
    actions = {
      [Util.CR] = function(state)
        if state.pattern:empty() then
          Repeat._states["jump"] = prevState
          -- would be nice to find a good way to do this without schedule, to avoid the window flashing
          vim.schedule(function()
            flashJump(true)
          end)
          return false
        else
          state:jump()
          return false
        end
      end,
    },
    abort = function()
      aborted = true
    end,
  }
  local state = Repeat.get_state("jump", opts)
  state:loop(opts)
  if not state.pattern:empty() and aborted ~= true then
    prevState = state  -- don't overwrite state when <esc>
  end
end
```
