### ISSUE TITLE
feature: always label the 3rd character in jump mode

### ISSUE THREAD

**Issue by quantum-booty** [folke/flash.nvim#56]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

if I want to jump to 'mappings', I would press 's' then 'ma'.
Right after pressing 'm', flash puts a label 'f' on the 2nd character:
<img width="247" alt="image" src="https://github.com/folke/flash.nvim/assets/28958399/dbb970f6-8a5b-4004-832f-47ded51d0e3c">
Right after pressing 'a', it puts a label 'f' on the 3rd character:
<img width="218" alt="image" src="https://github.com/folke/flash.nvim/assets/28958399/7ca76d8f-01dc-45f6-bbb4-76fa93a7e214">

My problem is that this causes the label character to move around when I'm typing, and this causes some cognitive load which slows me down.

### Describe the solution you'd like

Always put the label on the 3rd character, like leap.nvim

### Describe alternatives you've considered

.

**Comment by folke** [comment]
```lua
{highlight = {label = {after = false, before = true}}}
```

**Comment by folke** [comment]
To put it on the 3rd character, set `before = {0, 2}`
