### ISSUE TITLE
feature: jump to first match

### ISSUE THREAD

**Issue by quantum-booty** [folke/flash.nvim#57]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

It would be great if I don't have to press enter to jump to the first match.

### Describe the solution you'd like

This would be a feature similar to auto_jump when there is a unique match, but this time it would jump to the first match, and the user can stop at that point.

### Describe alternatives you've considered

.

**Comment by folke** [comment]
How would that work exactly?

You mean jump to the first match after entering a fixed number of characters?

**Comment by quantum-booty** [comment]
yeah like after entering 2 characters.

**Comment by folke** [comment]
```lua
require("flash").jump({
  labels = "sdfgqwertyuopzxcvbnm",
  search = {
    max_length = 2,
    incremental = true,
  },
})
```

After entering two characters, you need to either use a jump label, or any other key.

When using another key, the jump ends and the other key is executed.

So `sooi` would go to the first occurence of `oo` and start instert mode.

The keys you want to be able to use should of course be removed from the `labels`.

**Comment by Ciel-MC** [comment]
> ```lua
> require("flash").jump({
>   labels = "sdfgqwertyuopzxcvbnm",
>   search = {
>     max_length = 2,
>     incremental = true,
>   },
> })
> ```
> 
> After entering two characters, you need to either use a jump label, or any other key.
> 
> When using another key, the jump ends and the other key is executed.
> 
> So `sooi` would go to the first occurence of `oo` and start instert mode.
> 
> The keys you want to be able to use should of course be removed from the `labels`.

Is it possible to do this "safe jump" without a character limit? As in your cursor is always placed on the closest(?) match, and continues to move as you continue typing.

**Comment by folke** [comment]
Yes, just don't use `max_length`, and set `incremental = true`

**Comment by Ciel-MC** [comment]
> Yes, just don't use `max_length`, and set `incremental = true`

Hm, it looks like even if there is only one match, it doesn't end the search, which I guess makes sense, but was a little unexpected.

What is more unexpected though, is that after I am on a target and press `a` or `i`, it did nothing, whereas I was expecting to go into insert mode. Is this intended? It looks like as of now, pressing other keys doesn't do the action, but instead just exits the search.

**Comment by folke** [comment]
just changed that. but only for incremental search

**Comment by Ciel-MC** [comment]
> just changed that. but only for incremental search

Fantastic, gave it a tiny and and it seems like it's working, than you.
