### ISSUE TITLE
bug: Doesn't work in "vscode-neovim" extension of vs code

### ISSUE THREAD

**Issue by edicon** [folke/flash.nvim#58]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

MacOS 13.4.1

### Describe the bug

-Doesn't work in "vscode-neovim" extension(https://github.com/vscode-neovim/vscode-neovim) environment of vs code

### Steps To Reproduce

1. install vs code
2. install vscode-neovim extension
3. Install neovim 0.8.0 or greater
4. install flash.nvim and setup
5. run vs code
6. enter / to search

### Expected Behavior

The label should appear when you search. Label and highlight do not work properly

**Comment by archilkarchava** [comment]
Highlighting is best-effort https://github.com/vscode-neovim/vscode-neovim/issues/1143#issuecomment-1424086248 in vscode-neovim, so some highlights display incorrectly or don't display at all.

I'm using the following highlights to make it work in VS Code:
```lua
init = function()
	local function set_highlights()
		vim.api.nvim_set_hl(0, "FlashLabel", {
			fg = "#ff0000", bold = true, nocombine = true,
		})
		vim.api.nvim_set_hl(0, "FlashBackdrop", { fg = "gray" })
	end
	vim.api.nvim_create_autocmd({ "ColorScheme" }, {
		callback = set_highlights,
	})
end
```

**Comment by folke** [comment]
@archilkarchava thank you for the work-around!

Will see if I can add vscode support this way out of the box.

**Comment by folke** [comment]
I've made some changes to Flash specifically for VS Code:

- **VS Code**: some functionality is changed/disabled when running **flash** in **VS Code**:
  - `prompt` is disabled
  - `highlights` are set to different defaults that will actually work in VS Code
  - `search.multi_window` is disabled, since VS Code has problems with `vim.api.nvim_set_current_win`

See also: https://github.com/vscode-neovim/vscode-neovim/issues/1241

**Comment by theol0403** [comment]
FYI, the reason why the default highlights don't work in VSCode is that it blocks all "Syntax" hl groups by default for performance and to avoid clashes with syntax highlighting. Thus, the "Comment" group is blocked, for example.

Ideally, this can be fixed, where we can *tell* nvim not to send syntax highlights, but we can still have the highlight groups rendered. Ref: https://github.com/vscode-neovim/vscode-neovim/issues/519#issuecomment-1203125253

**Comment by theol0403** [comment]
The issue is linking to a blocked group, like "Comment".

https://github.com/vscode-neovim/vscode-neovim/blob/86ca759e154bf2f99ae031e70aa49aa1b22b9452/package.json#L192C24-L192C24

**Comment by folke** [comment]
ok, gotcha. That's why the links didn't work probably.

**Comment by folke** [comment]
but again, the defaults are terrible, so better to have custom highlghts for vscode anyway.

**Comment by theol0403** [comment]
Btw, if you think you can improve the defaults, PRs are always welcome! I'm not entirely sure what would need to be done to improve them -- though, it is actually possible to grab highlights from the vscode theme. https://github.com/vscode-neovim/vscode-neovim/blob/86ca759e154bf2f99ae031e70aa49aa1b22b9452/package.json#L244C25-L244C25
