### ISSUE TITLE
feature: Eyeliner integration

### ISSUE THREAD

**Issue by TSoli** [folke/flash.nvim#63]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

The character search does not work with [eyeliner](https://github.com/jinh0/eyeliner.nvim). One or the other plugin breaks (it seems depending on the order that they are loaded? - i.e I tried uninstalling and reinstalling each and got different results depending on the order).

### Describe the solution you'd like

I think having the initial highlighting similar to eyeliner would make this mode fantastic. Most of the time I want to go to a specific word when using f/t and eyeliner does a great job of this. The continued search that this plugin offers could also be fairly useful so if they could play nicely together that would be amazing (either by integrating this feature into flash or figuring out some way of making them work together).

### Describe alternatives you've considered

I guess the alternative would be to disable this feature in flash or uninstall eyeliner. These options work as expected afaik.

**Comment by folke** [comment]
You won't be able to use both at the same time, since both plugins override the same keymaps.

I'm also not interested in adding eyeliner functionality to flash.

**Comment by willothy** [comment]
> I'm also not interested in adding eyeliner functionality to flash.

I'm currently working on implementing this for my own config - would you be interested in a PR, or are you not interested in including the feature at all?

**Comment by folke** [comment]
Depends on what exactly it would do :)

Never used that plugin.

But I assume it would only do something when you havent typed a char yet? so right after `f` for example?

**Comment by willothy** [comment]
> But I assume it would only do something when you havent typed a char yet? so right after `f` for example?

Yes, it gives optimal jump locations for words in the chosen direction, highlighting locations that can be jumped to with a single char or a repeat of a single char. [My implementation](https://github.com/willothy/nvim-config/blob/b3c2f3701373070a511ee8b0fb1d386257d93f7c/lua/plugins/navigation/flash.lua#L83) is a bit messy so far and I'm not quite sure how it would fit in with the plugin overall, but here's what it looks like:

![2023-06-28 21-19-12 (2)](https://github.com/folke/flash.nvim/assets/38540736/2ed1b39d-8e4c-44fc-96df-9561b5455116)

**Comment by tizot** [comment]
If people are looking to do this, with the latest changes in `eyeliner`, it is possible to call its "highlight" method just before the `flash` behaviour is executed.

I used https://github.com/anuvyklack/keymap-amend.nvim to "extend" the mappings in my config:
```lua
{
  'folke/flash.nvim',
  opts = {
    modes = {
      char = {
        enabled = true,
      },
    },
  },
  config = function(_, opts)
    require('flash').setup(opts)
    local keymap = vim.keymap
    keymap.amend = require 'keymap-amend'
    local Eyeliner = require 'eyeliner'

    for key, forward in pairs { f = true, F = false, t = true, T = false } do
      keymap.amend({ 'n', 'o', 'x' }, key, function(original)
        Eyeliner.highlight { forward = forward }
        original()
      end)
    end
  end,
}
```
