### ISSUE TITLE
bug: the behavior is weird when search last pattern with `//` or `??`

### ISSUE THREAD

**Issue by gpncarl** [folke/flash.nvim#67]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-575+ge59cf3b3a9

### Operating system/version

archlinux 6.3.9-arch1-1 

### Describe the bug

the behavior is weird when search last pattern with `//` or `??`
as the picture shown, it highlight both slash and `include`(the last pattern)
![图片](https://github.com/folke/flash.nvim/assets/38633718/9a7f53fb-788f-472f-9f9e-67cffea89f29)

### Steps To Reproduce

1. search any word
2. type `//` to search last word

### Expected Behavior

only highlight last pattern with label

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "folke/flash.nvim", opts = {} },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Should be fixed now. Added support for search-commands
