### ISSUE TITLE
bug: Adds the typed pattern rather than the search string to the search register & history

### ISSUE THREAD

**Issue by IndianBoy42** [folke/flash.nvim#7]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-541+g96b94f8d7

### Operating system/version

Pop!_OS 22.04 LTS

### Describe the bug

I'm not sure if this is a bug or a misunderstand + feature request in some sense. When flash is configured to add to the search register and history, what is added is actually what the user types, not the actual search string that is used (which is different in the case of exact and even moreso in fuzzy mode) 

It would seem the use case of the option is to make it easily repeatable. If the search string were added to the search register than `n, N` should just work afaict. But as it is it doesn't 

I think this should be `state.pattern.search`?
https://github.com/folke/flash.nvim/blob/41fab4cb225d9233fec7987bb1445c9768d84caf/lua/flash/jump.lua#L50

### Steps To Reproduce

1. set `opts.jump.register = true` and `opts.search.mode = "fuzzy"`
2. Use the jump (`srg...`)
3. Check the search register with `"/p`
4. Try repeating the search with "n"

### Expected Behavior

I would expect the search register to be filled with the augmented search string that makes it a fuzzy search. 
It would seem the use case of the option is to make it easily repeatable. If the search string were added to the search register than `n, N` should just work afaict. But as it is i'm not sure how to easily repeat fuzzy search. 

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	"folke/tokyonight.nvim",
	{
		"folke/flash.nvim",
		opts = {
			search = {
				mode = "fuzzy",
			},
			jump = {
				register = true,
				history = true,
			},
		},
		keys = {
			{
				"s",
				mode = { "n", "x", "o" },
				function()
					-- default options: exact mode, multi window, all directions, with a backdrop
					require("flash").jump()
				end,
			},
		},
	},
	-- add any other plugins here
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Good point, changed it to use `pattern.search` instead
