### ISSUE TITLE
bug: labels are continuation of the search pattern

### ISSUE THREAD

**Issue by rasulomaroff** [folke/flash.nvim#71]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

MacOS 14.0

### Describe the bug

It's said:

> Labels are guaranteed not to exist as a continuation of the search pattern.

, but I have situations where they are a continuation.

### Steps To Reproduce

![WezTerm 2023-06-27 at 02-22](https://github.com/folke/flash.nvim/assets/80093436/d9a2ffda-584b-4555-8514-7ba2af26917a)
![WezTerm 2023-06-27 at 02-22](https://github.com/folke/flash.nvim/assets/80093436/5dd7c72c-f5f0-4a85-8a75-7b135077a6c4)

### Expected Behavior

I expected it not to be a continuation of the search pattern. I added my plugin options so that you can see when it doesn't work.

I think the issue happens when I combine `search.max_length` and `highlight.label.min_pattern_length` properties.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "folke/flash.nvim",
    opts = {
      labels = 'setnriaogkfuplwyqbjdhvmcxz',
      search = { max_length = 2 },
      highlight = {
        label = {
          min_pattern_length = 2
        }
      }
    }
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by IndianBoy42** [comment]
Isn't this expected? Labels are not a continuation of the pattern so you can keep typing the pattern, you set max_length=2 and then typed 2 characters, so there is no more need to allow continuing the pattern. The goal of max_length is to open up the space to use all the labels

**Comment by folke** [comment]
That's to be expected with your config like @IndianBoy42 mentions

**Comment by rasulomaroff** [comment]
@IndianBoy42 yes, you're right here, but wouldn't it be more obvious to put "e" label near words that have it as a continuation? I mean, in this case it can be near the first 2 words "**pr**e", instead of near the word "ex**pr**". Or it doesn't make sense, then why?
