### ISSUE TITLE
bug: Fuzzy search ranking

### ISSUE THREAD

**Issue by titouancreach** [folke/flash.nvim#73]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.1

### Operating system/version

MAC OS 13.4 Beta (22F5027f)

### Describe the bug

Fuzzy search ranking is not perfect:

<img width="982" alt="Screenshot 2023-06-27 at 11 04 20" src="https://github.com/folke/flash.nvim/assets/3995719/74337d73-f3b9-4bbb-864e-d4d5634fe345">

In this screenshot, I did "s + space" and my keybinding is mapped to:

```lua
  {
      "s",
      mode = { "n", "x", "o" },
      function()
          -- default options: multi window, all directions, with a backdrop
          require("flash").jump()
      end,
      desc = "Flash",
  }
```

### Steps To Reproduce

See screenshot

### Expected Behavior

**s**.normal_mode["<C-s**pace**"] is found. instead of <C-Space> that should be ranked first.
I believe the fuzzy is "too much fuzzy" or maybe, if there is collision between two matches, we shoud choose the "more exact"

**Comment by folke** [comment]
Can you please provide your full settings and some text that shows the issue? Not a screenshot, but actual text I can copy paste instead of typing over...

**Comment by titouancreach** [comment]
Oh yes sorry:

```
bonfoorbarbonjourfoorbar
```

with

```lua
    {
        "folke/flash.nvim",
        event = "VeryLazy",
        ---@type Flash.Config
        opts = {
            search = {
                mode = "fuzzy"
            }
        },
        keys = {
            {
                "s",
                mode = { "n", "x", "o" },
                function()
                    -- default options: exact mode, multi window, all directions, with a backdrop
                    require("flash").jump()
                end,
                desc = "Flash",
            }
        },
    },

``` 

should be enough. Then type "s" to enter search mode and type "bonjour". The highlighted par is
```
bonfoorbarbonjour
```

But, there is a closer match (exact match) that is not labeled (bonjour at the end)

**Comment by folke** [comment]
I see what you mean. That's a limitation of the fuzzy search implementation
There's no way to make this work the way you want with vim regex. I'm already using non greedy search patterns,
but vim's implementation still prefers matches closer to the cursor.
