### ISSUE TITLE
bug: treesitter_search does not select the last character if selection is "exclusive"

### ISSUE THREAD

**Issue by isaksamsten** [folke/flash.nvim#81]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

MacOS

### Describe the bug

When using `require("flash").treesitter_search()` with `set selection=exclusive` the last character of the treesitter search is not selected.

### Steps To Reproduce

1. `set selection=exclusive`
2. `require("flash").treesitter_search()`
3. Select a node
4. Observe that the last character is not selected

### Expected Behavior

Respect the behaviour of `set selection=exclusive`. 

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "folke/flash.nvim", opts = {} },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
vim.opt.selection = "exclusive"
```

**Comment by isaksamsten** [comment]
I don’t think that behaviour is natural with regards to how exclusive selection works (but you are of course free to disagree).

Given the intent of selecting the treesitter node, the full node (including the last char) should be selected. Consider `V` to select the full line, this operation does not exclude the last char with `selection=exclusive`. Similarly, `vf<char>` selects until and including `<char>` no matter the type of selection setting.

**Comment by folke** [comment]
There's no proper way to force inclusive when selection is set in Neovim.

I added the below, that seems to work:

```lua
function M.fix_selection()
  local selection = vim.go.selection
  vim.go.selection = "inclusive"
  vim.schedule(function()
    vim.go.selection = selection
  end)
end
```

It may have unexpected consequences though...

**Comment by isaksamsten** [comment]
Cool! Thanks!
