### ISSUE TITLE
feature: Uppercase-only labels and possibly double-character labels

### ISSUE THREAD

**Issue by mystilleef** [folke/flash.nvim#84]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

Is it possible to provide uppercase-only labels that are activated by lowercase keys on the keyboard? I find lowercase labels are harder to read as they often blend in with none label characters in the buffer.

### Describe the solution you'd like

`Hop` solves this problem by allowing users to display labels in uppercase only. When uppercase labels run out, `Hop` then shows double-character uppercase labels.

Even though the labels are displayed in uppercase they're activated using lowercase keys on the keyboard. No `shift` key is needed.

In addition, `Hop` provides highlight colors for each character in a label, be it single or double, to allow even easier and quicker identification and separation. 

### Describe alternatives you've considered

Currently, I modify highlight colors to make labels pop and stand out a little more. However, I still have to spend an extra moment or so verifying labels are not just characters in the buffer. This is a problem I never had with `Hop`.

### Additional context

See the screenshot below for `HopWord` in action.

![hop_example](https://github.com/folke/flash.nvim/assets/273399/5609fb91-fd7f-496d-b4ec-31214f7274c8)

**Comment by folke** [comment]
You can now do something like:

```lua
    opts = {
      label = {
        format = function(opts)
          return { { opts.match.label:upper(), opts.hl_group } }
        end,
      },
   }
```

I'll think about 2char labels, but since flash is search based, I don't really see why that would be needed...

**Comment by folke** [comment]
Also check the hop example in the readme for 2char jumping similar to hop and jump2d

**Comment by brookhong** [comment]
> You can now do something like:
> 
> ```lua
>     opts = {
>       label = {
>         format = function(opts)
>           return { { opts.match.label:upper(), opts.hl_group } }
>         end,
>       },
>    }
> ```
> 
> I'll think about 2char labels, but since flash is search based, I don't really see why that would be needed...

I just confirm there is an issue with this setting, if both `a` and `A` come as labels, you will see two `A`.
