### ISSUE TITLE
feature: Allow '/' search to continue even with no matches

### ISSUE THREAD

**Issue by yodigi7** [folke/flash.nvim#85]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

When using the '/' character to search the whole file for a potentially existing word. If the word doesn't exist it will automatically exit the search mode once it fails to match any words on the file.
This can be annoying when you have a very large file and just want to check to see if a word is in the file and then all of a sudden you are adding text into the buffer since it quit searching partway through your search.

### Describe the solution you'd like

The search doesn't auto return to normal mode once no matches have been found before hitting Enter/Escape.

### Describe alternatives you've considered

Have a setting in the config file to allow current behavior or potential updated behavior.
Have a more obvious indication such as a screen flash or something once the search has been terminated due to no results.

**Comment by folke** [comment]
regular search is never terminated by flash.
What likely happens is that you enter a character and then a label since the followup character does not exist.
