### ISSUE TITLE
bug: `<C-f>` keymap conflicts with `f` 

### ISSUE THREAD

**Issue by Pheon-Dev** [folke/flash.nvim#87]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

Arch Linux 6.3.9-arch1-1

### Describe the bug

`<C-f>` is currently used by `karb94/neoscroll.nvim` to scroll forward but `f` conflicts with it yet it's only mapped to just `f`. Thanks. 

### Steps To Reproduce

1. add `karb94/neoscroll.nvim`
2. use the default configs
3. reload and try scrolling through a long file with `<C-f>`

### Expected Behavior

`f` to still work as it does but should not be triggered by `<C-f>`

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "folke/flash.nvim", opts = {} },
  -- add any other plugins here
	{
		"karb94/neoscroll.nvim",
		event = "VeryLazy",
		config = function()
			local ok, neoscroll = pcall(require, "neoscroll")

			if not ok then
				return
			end

			neoscroll.setup({})
		end,
	},

}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by Pheon-Dev** [comment]
Thanks for yet another awesome plugin that replaces almost 5 others I had, I've got 70+ plugins and almost half of them are from you. Big up, such an inspiration.

**Comment by folke** [comment]
thanks!

Flash only maps `f`, so not sure what neoscroll does to trigger it.

Best to check there.

Something like this could also be caused by a broken keyboard setup where repeated `<c-f>`, only emits `f`.

No idea, but for sure not caused by flash
