### ISSUE TITLE
bug: treesitter_search with NvimTree causes catastrophic failure

### ISSUE THREAD

**Issue by i40west** [folke/flash.nvim#91]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.1

### Operating system/version

macOS 13.4.1

### Describe the bug

I tried the new treesitter_search by pasting the config section from the docs.

```
            {
                "R",
                mode = { "o", "x" },
                function()
                    require("flash").treesitter_search()
                end,
                desc = "Flash Treesitter Search",
            },
```
After invoking the mode, if NvimTree is open, any keystroke throws an error:

`E5108: Error executing lua: ...0.9.1/share/nvim/runtime/lua/vim/treesitter/language.lua:94: no parser for 'NvimTree' language, see :help treesitter-parsers`

At this point, every keystroke is an error and the only way to continue is to kill the editor. It happens only if NvimTree is open. Minimal `repro.lua` included below.

### Steps To Reproduce

1. Add the config section and restart nvim.
2. Open NvimTree (`:NvimTreeToggle`), then focus back on the editor window.
3. Do `vR` or `yR`, etc. The flash mode is entered.
4. Type any character.

### Expected Behavior

Behold the wonder of treesitter_search

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
     {
        'folke/flash.nvim',
        config = function()
            require('flash').setup {}
        end,
        keys = {
            {
                "R",
                mode = { "o", "x" },
                function()
                    require("flash").treesitter_search()
                end,
                desc = "Flash Treesitter Search",
            },
        },
    },
    {
        'nvim-tree/nvim-tree.lua',
        config = true,
    },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Good catch! Fixed now! :)
