### ISSUE TITLE
feature:  f,F,T,t - with labels - make first label same as typed in motion letter

### ISSUE THREAD

**Issue by JoseConseco** [folke/flash.nvim#92]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

When using f, t, F, T with labels  (from exaples), I thought it would be cool 
if  first label would be same as motion.  For example when using:
dty   - it will label all `y` -  with various letters - but it could mark first occurrence of `y` with "y" label.
This way you if u know the searched letter is first in line - u could just do:
dtyy   - auto jump to first y. 

### Describe the solution you'd like

some option to make first label same as motion character

### Describe alternatives you've considered

I do not think any other plugin has this feature. 

### Additional context

Maybe it could be used for other  jumps?  
Lets say we search for  word  'example' 
we type '/exa`a`' - it would jump to first match of  word 'exa' .

**Comment by folke** [comment]
I just pushed a lot of new changes and smart labeled ftFT searches are now included.

You can repeat a jump the same way as without labels using `f` and `t` for next, `F` and `T` for prev. 

Use the below configuration.

```lua
 opts = {
      modes = {
        char = {
          jump_labels = function(motion)
            -- never show jump labels by default
            -- return false
            -- Always show jump labels for ftFT
            return vim.v.count == 0 and motion:find("[ftFT]")
            -- Show jump labels for ftFT in operator-pending mode
            -- return vim.v.count == 0 and motion:find("[ftFT]") and vim.fn.mode(true):find("o")
          end,
        },
      },
    },
```

It combines ftFT searches with labels. You can still navigate clever-f style or use `;`, `,` as well. A lot of labels are also excluded, so you can continue from the new position with any key like `hjklia...`

It pretty much combines the best of both worlds :)
you can also only enable it for operator pending mode or any other conditions.

Let me know what you think!

**Comment by JoseConseco** [comment]
@folke it works great, and it can be repeated so that is cool.   I think there is small bug where if I  . repeat, it will delete till next 'b' ok - but it will shown all 'b' labels .    In video I did  dtb - then . repeat few times : 

https://github.com/folke/flash.nvim/assets/13521338/3e83ac3a-d1b2-42e6-bbb1-8e63e4769d7e

You can see all the 'b' labels are shown on . repeat.

**Comment by folke** [comment]
That's not a bug. Repeats use regular mode (non-jumping labels), since it wouldn't make a lot of sense to having to enter a jump label again
