### ISSUE TITLE
bug: ReplaceWithRegister <Plug>ReplaceWithRegisterOperator doesn't work with `remote`

### ISSUE THREAD

**Issue by TheLeoP** [folke/flash.nvim#93]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.1 Build type: RelWithDebInfo

### Operating system/version

Ubuntu 22.04.2 LTS

### Describe the bug

Using `require("flash").remote()` with `<Plug>ReplaceWithRegisterOperator` from [ReplaceWithRegister](https://github.com/vim-scripts/ReplaceWithRegister) doesn't work as expected. The text that is suppossed to be inserted in the selected location is also inserted at the starting location.

### Steps To Reproduce

1. `nvim -u repro.lua`
2. Open `example.txt` with the following code:

```
remote

starting

foo
```

3.Put the cursor on `foo` and highlight the word (`yiw`).
4. Put the cursor at the beggining of `starting`
5. Press the keys `<leader>r` to start a replace
6. Press `r` to execute `require("flash").remote()`
7. Press `re` and select the label next to `re` on the word `remote`
8. Press `iw`

The result is the following:

```
foo

foostarting

foo
```

The text was replaced on the remote location, but it was also inserted at the starting location.

### Expected Behavior

The result should be the following

```
foo

starting

foo
```

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	"folke/tokyonight.nvim",
	{
		"folke/flash.nvim",
		opts = {},
		keys = {
			{
				"r",
				mode = "o",
				function()
					require("flash").remote()
				end,
				desc = "Remote Flash",
			},
		},
	},
	-- add any other plugins here
	{
		"vim-scripts/ReplaceWithRegister",
		keys = {
			{ "<leader>r", "<Plug>ReplaceWithRegisterOperator", mode = "n" },
		},
	},
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
This turned out to be a really tricky issue. I has to spend way too much time in solving this :)

The solution was eventually really simple, but not that straightforeward.

Either way, this should be fixed now :)

Thank you for the detailed bug reprort!
