### ISSUE TITLE
bug: Label Conflict with Multi-Window Same Buffer

### ISSUE THREAD

**Issue by sigurduraegir** [folke/flash.nvim#97]
### Did you check docs and existing issues?

- [X] I have read all the flash.nvim docs
- [X] I have searched the existing issues of flash.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.0

### Operating system/version

Ubuntu 22.10

### Describe the bug

When the same buffer is open in two windows, with overlapping visible text in both windows, flash.nvim generates the same label on both buffers upon invoking a jump command. This creates a situation where it's not possible to select a specific buffer to jump to. It's possible this is an unintended consequence of the current design when dealing with this particular use case. If I am missing a configuration somewhere or if this is the intended behavior, I apologize.

Thank you for your work on flash.nvim. It's a fantastic plugin, and even in its early stages, it's already the best I have used.

### Steps To Reproduce

1. Open the same buffer in two separate windows.
2. Ensure some portion of the visible text is the same in both windows.
3. Invoke a jump command.

### Expected Behavior

The labels generated for jumps should be unique to each buffer, even when the same buffer is open in two windows. This should allow a user to select a specific buffer to jump to.

**Comment by folke** [comment]
That's unfortunately not possible, since extmarks (the labels and highlights and such), are bound to a buffer, not a window.

There's currently no way in Neovim to show a different label for the same buffer in a different window.

**Comment by sigurduraegir** [comment]
Thank you for your quick response and for clarifying the situation. I didn't realize the constraints with extmarks being bound to a buffer, not a window. I appreciate your explanation and your work.
