### ISSUE TITLE
feature: operator-less remote actions

### ISSUE THREAD

**Issue by Reisen** [folke/flash.nvim#98]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

Remote requires operator pending, this is useful if the edit operation is an operator but there are non-operator operations that are also useful that can't be performed that add some friction to editing, such as the inability to undo a remote operation easily.

### Describe the solution you'd like

I would like to be able to perform remote `D` and `u` style operations. For example, often after performing a remote delete in another window, that I then want to undo, I have to move to that window for the undo to work. But a more natural movement would be `r<match>u` to remotely undo. Or for example in the following where I've placed labels under each line to show the movement I would like to make:

```
opt_a, -- Option A
     [ -a]
opt_b,
     [ -b]
```

Would be useful to be able to delete the comment with `r -aD` to delete to the end of the line on opt_a.

Another example might be that I have a macro I want to apply at a remote location, `rab<label>@a`. There are many other things like this that can't be done without operators I think.

### Describe alternatives you've considered

There's nothing quite like this, except perhaps `avy` in the Emacs world which allows defining custom actions. Avy works slightly differently to flash so allows for this as it is limited to two characters only, so the third character can always be an action (where the label set has defined actions removed), for example jumping to `ab` and performing an action in Avy in emacs would involve:

`sabD<label>`

Which works very well.

### Additional context

I think the main difficulty in implementing this is how to detect when to jump back when the action is rather arbitrary because flash allows unlimited characters, in avy your input is buffered until you hit the label char, so for example a jump might involve a selection and an edit: `rvaby` to yank a remote block which feels more natural than `yr...vab` ( which doesn't work anyway with current flash, though I realise is rather a synthetic example as you can just `yr...ab` ) but detecting the right moment to jump back is difficult, maybe impossible.

Anyway just spitballing ideas here because remote editing feels so close to being as powerful as Emacs avy, but not quite there, and flash has a great implementation to build around.

**Comment by folke** [comment]
Why don't you just use `s<match>u<c-o>`?

**Comment by Reisen** [comment]
Hmm, I mean that's definitely a fair answer, but by that same thought what's the need for having remote actions at all as I can do`s<match>dd<c-o>` over `dr<match>d`. Your point is valid but it applies to existing remote actions I would've thought as well. The remote flow feels more fluid, so I'm just thinking of ways it could be more expansive.

**Comment by Reisen** [comment]
@folke Sweet, that set me along the right path to get exactly what I want using augroups, it relies on TextChanged and I'll extend it to Yank based events too which should cover all the use cases I personally can imagine needing, actually seems to work for exactly anything I would need. Any remote operation will result in a modification or a yank, so it's perfect:

```
keys = {
    { 'r', mode = { 'n' }, function()
        local state = require 'flash'.jump {
            remote_op = { restore = false }
        }

        vim.api.nvim_create_autocmd('TextChanged', {
            once     = true,
            buffer   = vim.api.nvim_get_current_buf(),
            callback = function(ev)
                state:restore()
            end
        })
    end, 'Flash Remote'}
}
```
